// Code generated by app-config; DO NOT EDIT.

package config

type Config struct {
	Admin       Admin       `json:"admin" koanf:"admin"`
	App         App         `json:"app" koanf:"app"`
	Auth        Auth        `json:"auth" koanf:"auth"`
	ConfigPath  string      `json:"-" koanf:"-"`
	Email       Email       `json:"email" koanf:"email"`
	Features    Features    `json:"features" koanf:"features"`
	Google      Google      `json:"google" koanf:"google"`
	Network     Network     `json:"network" koanf:"network"`
	Persistence Persistence `json:"persistence" koanf:"persistence"`
	Public      Public      `json:"public" koanf:"public"`
	Reminders   Reminders   `json:"reminders" koanf:"reminders"`
	Runtime     Runtime     `json:"runtime" koanf:"runtime"`
	Server      Server      `json:"server" koanf:"server"`
	Services    Services    `json:"services" koanf:"services"`
	Signer      Signer      `json:"signer" koanf:"signer"`
	Storage     Storage     `json:"storage" koanf:"storage"`
}

type Admin struct {
	APIPrefix     string `json:"api_prefix" koanf:"api_prefix"`
	APIVersion    string `json:"api_version" koanf:"api_version"`
	BasePath      string `json:"base_path" koanf:"base_path"`
	Debug         Debug  `json:"debug" koanf:"debug"`
	DefaultLocale string `json:"default_locale" koanf:"default_locale"`
	PublicAPI     bool   `json:"public_api" koanf:"public_api"`
	Title         string `json:"title" koanf:"title"`
}

type App struct {
	Env  string `json:"env" koanf:"env"`
	Name string `json:"name" koanf:"name"`
}

type AssetPermissions struct {
	Certificate []string `json:"certificate" koanf:"certificate"`
	Executed    []string `json:"executed" koanf:"executed"`
	Preview     []string `json:"preview" koanf:"preview"`
	Source      []string `json:"source" koanf:"source"`
}

type Auth struct {
	AdminEmail    string `json:"admin_email" koanf:"admin_email"`
	AdminID       string `json:"admin_id" koanf:"admin_id"`
	AdminPassword string `json:"admin_password" koanf:"admin_password"`
	AdminRole     string `json:"admin_role" koanf:"admin_role"`
	ContextKey    string `json:"context_key" koanf:"context_key"`
	SeedFile      string `json:"seed_file" koanf:"seed_file"`
	SigningKey    string `json:"signing_key" koanf:"signing_key"`
}

type Command struct {
	Args        []string `json:"args" koanf:"args"`
	Bin         string   `json:"bin" koanf:"bin"`
	MaxLogBytes int      `json:"max_log_bytes" koanf:"max_log_bytes"`
	MaxPdfBytes int64    `json:"max_pdf_bytes" koanf:"max_pdf_bytes"`
	TimeoutMS   int      `json:"timeout_ms" koanf:"timeout_ms"`
}

type Debug struct {
	EnableSlog bool `json:"enable_slog" koanf:"enable_slog"`
}

type Email struct {
	SMTP      SMTP   `json:"smtp" koanf:"smtp"`
	Transport string `json:"transport" koanf:"transport"`
}

type Features struct {
	Activity    bool `json:"activity" koanf:"activity"`
	ESign       bool `json:"esign" koanf:"esign"`
	ESignGoogle bool `json:"esign_google" koanf:"esign_google"`
}

type Fs struct {
	BasePath string `json:"base_path" koanf:"base_path"`
}

type Google struct {
	ClientID              string `json:"client_id" koanf:"client_id"`
	ClientSecret          string `json:"client_secret" koanf:"client_secret"`
	CredentialActiveKey   string `json:"credential_active_key" koanf:"credential_active_key"`
	CredentialActiveKeyID string `json:"credential_active_key_id" koanf:"credential_active_key_id"`
	CredentialKeysJSON    string `json:"credential_keys_json" koanf:"credential_keys_json"`
	DriveBaseURL          string `json:"drive_base_url" koanf:"drive_base_url"`
	HTTPTimeoutSeconds    int    `json:"http_timeout_seconds" koanf:"http_timeout_seconds"`
	HealthEndpoint        string `json:"health_endpoint" koanf:"health_endpoint"`
	OAuthRedirectURI      string `json:"oauth_redirect_uri" koanf:"oauth_redirect_uri"`
	ProviderMode          string `json:"provider_mode" koanf:"provider_mode"`
	RevokeEndpoint        string `json:"revoke_endpoint" koanf:"revoke_endpoint"`
	TokenEndpoint         string `json:"token_endpoint" koanf:"token_endpoint"`
	UserInfoEndpoint      string `json:"userinfo_endpoint" koanf:"userinfo_endpoint"`
}

type Migrations struct {
	LocalDir  string `json:"local_dir" koanf:"local_dir"`
	LocalOnly bool   `json:"local_only" koanf:"local_only"`
}

type Network struct {
	RateLimit                  RateLimit `json:"rate_limit" koanf:"rate_limit"`
	RateLimitTrustProxyHeaders bool      `json:"rate_limit_trust_proxy_headers" koanf:"rate_limit_trust_proxy_headers"`
	TrustedProxyCIDRs          []string  `json:"trusted_proxy_cidrs" koanf:"trusted_proxy_cidrs"`
}

type Pdf struct {
	AllowEncrypted         bool        `json:"allow_encrypted" koanf:"allow_encrypted"`
	AllowJavaScriptActions bool        `json:"allow_javascript_actions" koanf:"allow_javascript_actions"`
	CompatibilityMode      string      `json:"compatibility_mode" koanf:"compatibility_mode"`
	MaxDecompressedBytes   int64       `json:"max_decompressed_bytes" koanf:"max_decompressed_bytes"`
	MaxObjects             int         `json:"max_objects" koanf:"max_objects"`
	MaxPages               int         `json:"max_pages" koanf:"max_pages"`
	MaxSourceBytes         int64       `json:"max_source_bytes" koanf:"max_source_bytes"`
	NormalizationTimeoutMS int         `json:"normalization_timeout_ms" koanf:"normalization_timeout_ms"`
	ParseTimeoutMS         int         `json:"parse_timeout_ms" koanf:"parse_timeout_ms"`
	PipelineMode           string      `json:"pipeline_mode" koanf:"pipeline_mode"`
	PreviewFallbackEnabled bool        `json:"preview_fallback_enabled" koanf:"preview_fallback_enabled"`
	Remediation            Remediation `json:"remediation" koanf:"remediation"`
}

type Persistence struct {
	Migrations Migrations `json:"migrations" koanf:"migrations"`
	Postgres   Postgres   `json:"postgres" koanf:"postgres"`
	SQLite     Sqlite     `json:"sqlite" koanf:"sqlite"`
}

type Postgres struct {
	DSN string `json:"dsn" koanf:"dsn"`
}

type Public struct {
	BaseURL string `json:"base_url" koanf:"base_url"`
}

type RateLimit struct {
	AdminResend   SignerSession `json:"admin_resend" koanf:"admin_resend"`
	SignerConsent SignerSession `json:"signer_consent" koanf:"signer_consent"`
	SignerSession SignerSession `json:"signer_session" koanf:"signer_session"`
	SignerSubmit  SignerSession `json:"signer_submit" koanf:"signer_submit"`
	SignerWrite   SignerSession `json:"signer_write" koanf:"signer_write"`
}

type Remediation struct {
	AutoOnUpload     bool     `json:"auto_on_upload" koanf:"auto_on_upload"`
	CandidateReasons []string `json:"candidate_reasons" koanf:"candidate_reasons"`
	Command          Command  `json:"command" koanf:"command"`
	Enabled          bool     `json:"enabled" koanf:"enabled"`
	ExecutionMode    string   `json:"execution_mode" koanf:"execution_mode"`
	LeaseTTLMS       int      `json:"lease_ttl_ms" koanf:"lease_ttl_ms"`
}

type Reminders struct {
	AllowOutOfOrder             bool   `json:"allow_out_of_order" koanf:"allow_out_of_order"`
	BatchSize                   int    `json:"batch_size" koanf:"batch_size"`
	ClaimLeaseSeconds           int    `json:"claim_lease_seconds" koanf:"claim_lease_seconds"`
	Enabled                     bool   `json:"enabled" koanf:"enabled"`
	InitialDelayMinutes         int    `json:"initial_delay_minutes" koanf:"initial_delay_minutes"`
	IntervalMinutes             int    `json:"interval_minutes" koanf:"interval_minutes"`
	JitterPercent               int    `json:"jitter_percent" koanf:"jitter_percent"`
	ManualResendCooldownMinutes int    `json:"manual_resend_cooldown_minutes" koanf:"manual_resend_cooldown_minutes"`
	MaxReminders                int    `json:"max_reminders" koanf:"max_reminders"`
	RecentViewGraceMinutes      int    `json:"recent_view_grace_minutes" koanf:"recent_view_grace_minutes"`
	RotateToken                 bool   `json:"rotate_token" koanf:"rotate_token"`
	SweepCron                   string `json:"sweep_cron" koanf:"sweep_cron"`
}

type Runtime struct {
	Profile           string `json:"profile" koanf:"profile"`
	RepositoryDialect string `json:"repository_dialect" koanf:"repository_dialect"`
	StartupPolicy     string `json:"startup_policy" koanf:"startup_policy"`
	StrictStartup     bool   `json:"strict_startup" koanf:"strict_startup"`
}

type S3 struct {
	AccessKeyID     string `json:"access_key_id" koanf:"access_key_id"`
	BasePath        string `json:"base_path" koanf:"base_path"`
	Bucket          string `json:"bucket" koanf:"bucket"`
	DisableSsl      bool   `json:"disable_ssl" koanf:"disable_ssl"`
	EndpointURL     string `json:"endpoint_url" koanf:"endpoint_url"`
	Profile         string `json:"profile" koanf:"profile"`
	Region          string `json:"region" koanf:"region"`
	SecretAccessKey string `json:"secret_access_key" koanf:"secret_access_key"`
	SessionToken    string `json:"session_token" koanf:"session_token"`
	UsePathStyle    bool   `json:"use_path_style" koanf:"use_path_style"`
}

type SMTP struct {
	DisableSTARTTLS bool   `json:"disable_starttls" koanf:"disable_starttls"`
	FromAddress     string `json:"from_address" koanf:"from_address"`
	FromName        string `json:"from_name" koanf:"from_name"`
	Host            string `json:"host" koanf:"host"`
	InsecureTLS     bool   `json:"insecure_tls" koanf:"insecure_tls"`
	Password        string `json:"password" koanf:"password"`
	Port            int    `json:"port" koanf:"port"`
	TimeoutSeconds  int    `json:"timeout_seconds" koanf:"timeout_seconds"`
	Username        string `json:"username" koanf:"username"`
}

type SenderViewer struct {
	AssetPermissions          AssetPermissions `json:"asset_permissions" koanf:"asset_permissions"`
	CommentPermissionsAll     []string         `json:"comment_permissions_all" koanf:"comment_permissions_all"`
	PagePermissionsAll        []string         `json:"page_permissions_all" koanf:"page_permissions_all"`
	ShowInProgressFieldValues bool             `json:"show_in_progress_field_values" koanf:"show_in_progress_field_values"`
}

type Server struct {
	Address string `json:"address" koanf:"address"`
}

type Services struct {
	CallbackPublicBaseURL string `json:"callback_public_base_url" koanf:"callback_public_base_url"`
	EncryptionKey         string `json:"encryption_key" koanf:"encryption_key"`
	ModuleEnabled         bool   `json:"module_enabled" koanf:"module_enabled"`
}

type Signer struct {
	PDF                          Pdf          `json:"pdf" koanf:"pdf"`
	ProfileMode                  string       `json:"profile_mode" koanf:"profile_mode"`
	ProfilePersistDrawnSignature bool         `json:"profile_persist_drawn_signature" koanf:"profile_persist_drawn_signature"`
	ProfileTTLDays               int          `json:"profile_ttl_days" koanf:"profile_ttl_days"`
	SavedSignaturesLimitPerType  int          `json:"saved_signatures_limit_per_type" koanf:"saved_signatures_limit_per_type"`
	SenderViewer                 SenderViewer `json:"sender_viewer" koanf:"sender_viewer"`
	UploadSigningKey             string       `json:"upload_signing_key" koanf:"upload_signing_key"`
	UploadTTLSeconds             int          `json:"upload_ttl_seconds" koanf:"upload_ttl_seconds"`
}

type SignerSession struct {
	MaxRequests   int `json:"max_requests" koanf:"max_requests"`
	WindowSeconds int `json:"window_seconds" koanf:"window_seconds"`
}

type Sqlite struct {
	DSN string `json:"dsn" koanf:"dsn"`
}

type Storage struct {
	Backend             string `json:"backend" koanf:"backend"`
	EncryptionAlgorithm string `json:"encryption_algorithm" koanf:"encryption_algorithm"`
	Fs                  Fs     `json:"fs" koanf:"fs"`
	KmsKeyID            string `json:"kms_key_id" koanf:"kms_key_id"`
	S3                  S3     `json:"s3" koanf:"s3"`
}
