// Code generated by config-getters; DO NOT EDIT.

package config

// Config Getters

func (c Config) GetAdmin() Admin {
	return c.Admin
}

func (c Config) GetApp() App {
	return c.App
}

func (c Config) GetAuth() Auth {
	return c.Auth
}

func (c Config) GetConfigPath() string {
	return c.ConfigPath
}

func (c Config) GetEmail() Email {
	return c.Email
}

func (c Config) GetFeatures() Features {
	return c.Features
}

func (c Config) GetGoogle() Google {
	return c.Google
}

func (c Config) GetNetwork() Network {
	return c.Network
}

func (c Config) GetPersistence() Persistence {
	return c.Persistence
}

func (c Config) GetPublic() Public {
	return c.Public
}

func (c Config) GetReminders() Reminders {
	return c.Reminders
}

func (c Config) GetRuntime() Runtime {
	return c.Runtime
}

func (c Config) GetServer() Server {
	return c.Server
}

func (c Config) GetServices() Services {
	return c.Services
}

func (c Config) GetSigner() Signer {
	return c.Signer
}

func (c Config) GetStorage() Storage {
	return c.Storage
}

// Admin Getters

func (a Admin) GetAPIPrefix() string {
	return a.APIPrefix
}

func (a Admin) GetAPIVersion() string {
	return a.APIVersion
}

func (a Admin) GetBasePath() string {
	return a.BasePath
}

func (a Admin) GetDebug() Debug {
	return a.Debug
}

func (a Admin) GetDefaultLocale() string {
	return a.DefaultLocale
}

func (a Admin) GetPublicAPI() bool {
	return a.PublicAPI
}

func (a Admin) GetTitle() string {
	return a.Title
}

// App Getters

func (a App) GetEnv() string {
	return a.Env
}

func (a App) GetName() string {
	return a.Name
}

// Auth Getters

func (a Auth) GetAdminEmail() string {
	return a.AdminEmail
}

func (a Auth) GetAdminID() string {
	return a.AdminID
}

func (a Auth) GetAdminPassword() string {
	return a.AdminPassword
}

func (a Auth) GetAdminRole() string {
	return a.AdminRole
}

func (a Auth) GetContextKey() string {
	return a.ContextKey
}

func (a Auth) GetSeedFile() string {
	return a.SeedFile
}

func (a Auth) GetSigningKey() string {
	return a.SigningKey
}

// Command Getters

func (c Command) GetArgs() []string {
	return c.Args
}

func (c Command) GetBin() string {
	return c.Bin
}

func (c Command) GetMaxLogBytes() int {
	return c.MaxLogBytes
}

func (c Command) GetMaxPdfBytes() int64 {
	return c.MaxPdfBytes
}

func (c Command) GetTimeoutMS() int {
	return c.TimeoutMS
}

// Debug Getters

func (d Debug) GetEnableSlog() bool {
	return d.EnableSlog
}

// Email Getters

func (e Email) GetSMTP() SMTP {
	return e.SMTP
}

func (e Email) GetTransport() string {
	return e.Transport
}

// Features Getters

func (f Features) GetActivity() bool {
	return f.Activity
}

func (f Features) GetESign() bool {
	return f.ESign
}

func (f Features) GetESignGoogle() bool {
	return f.ESignGoogle
}

// Google Getters

func (g Google) GetClientID() string {
	return g.ClientID
}

func (g Google) GetClientSecret() string {
	return g.ClientSecret
}

func (g Google) GetCredentialActiveKey() string {
	return g.CredentialActiveKey
}

func (g Google) GetCredentialActiveKeyID() string {
	return g.CredentialActiveKeyID
}

func (g Google) GetCredentialKeysJSON() string {
	return g.CredentialKeysJSON
}

func (g Google) GetDriveBaseURL() string {
	return g.DriveBaseURL
}

func (g Google) GetHTTPTimeoutSeconds() int {
	return g.HTTPTimeoutSeconds
}

func (g Google) GetHealthEndpoint() string {
	return g.HealthEndpoint
}

func (g Google) GetOAuthRedirectURI() string {
	return g.OAuthRedirectURI
}

func (g Google) GetProviderMode() string {
	return g.ProviderMode
}

func (g Google) GetRevokeEndpoint() string {
	return g.RevokeEndpoint
}

func (g Google) GetTokenEndpoint() string {
	return g.TokenEndpoint
}

func (g Google) GetUserInfoEndpoint() string {
	return g.UserInfoEndpoint
}

// Migrations Getters

func (m Migrations) GetLocalDir() string {
	return m.LocalDir
}

func (m Migrations) GetLocalOnly() bool {
	return m.LocalOnly
}

// Network Getters

func (n Network) GetRateLimit() RateLimit {
	return n.RateLimit
}

func (n Network) GetRateLimitTrustProxyHeaders() bool {
	return n.RateLimitTrustProxyHeaders
}

func (n Network) GetTrustedProxyCIDRs() []string {
	return n.TrustedProxyCIDRs
}

// Pdf Getters

func (p Pdf) GetAllowEncrypted() bool {
	return p.AllowEncrypted
}

func (p Pdf) GetAllowJavaScriptActions() bool {
	return p.AllowJavaScriptActions
}

func (p Pdf) GetCompatibilityMode() string {
	return p.CompatibilityMode
}

func (p Pdf) GetMaxDecompressedBytes() int64 {
	return p.MaxDecompressedBytes
}

func (p Pdf) GetMaxObjects() int {
	return p.MaxObjects
}

func (p Pdf) GetMaxPages() int {
	return p.MaxPages
}

func (p Pdf) GetMaxSourceBytes() int64 {
	return p.MaxSourceBytes
}

func (p Pdf) GetNormalizationTimeoutMS() int {
	return p.NormalizationTimeoutMS
}

func (p Pdf) GetParseTimeoutMS() int {
	return p.ParseTimeoutMS
}

func (p Pdf) GetPipelineMode() string {
	return p.PipelineMode
}

func (p Pdf) GetPreviewFallbackEnabled() bool {
	return p.PreviewFallbackEnabled
}

func (p Pdf) GetRemediation() Remediation {
	return p.Remediation
}

// Persistence Getters

func (p Persistence) GetMigrations() Migrations {
	return p.Migrations
}

func (p Persistence) GetPostgres() Postgres {
	return p.Postgres
}

func (p Persistence) GetSQLite() Sqlite {
	return p.SQLite
}

// Postgres Getters

func (p Postgres) GetDSN() string {
	return p.DSN
}

// Public Getters

func (p Public) GetBaseURL() string {
	return p.BaseURL
}

// RateLimit Getters

func (r RateLimit) GetAdminResend() SignerSession {
	return r.AdminResend
}

func (r RateLimit) GetSignerConsent() SignerSession {
	return r.SignerConsent
}

func (r RateLimit) GetSignerSession() SignerSession {
	return r.SignerSession
}

func (r RateLimit) GetSignerSubmit() SignerSession {
	return r.SignerSubmit
}

func (r RateLimit) GetSignerWrite() SignerSession {
	return r.SignerWrite
}

// Remediation Getters

func (r Remediation) GetAutoOnUpload() bool {
	return r.AutoOnUpload
}

func (r Remediation) GetCandidateReasons() []string {
	return r.CandidateReasons
}

func (r Remediation) GetCommand() Command {
	return r.Command
}

func (r Remediation) GetEnabled() bool {
	return r.Enabled
}

func (r Remediation) GetExecutionMode() string {
	return r.ExecutionMode
}

func (r Remediation) GetLeaseTTLMS() int {
	return r.LeaseTTLMS
}

// Reminders Getters

func (r Reminders) GetAllowOutOfOrder() bool {
	return r.AllowOutOfOrder
}

func (r Reminders) GetBatchSize() int {
	return r.BatchSize
}

func (r Reminders) GetClaimLeaseSeconds() int {
	return r.ClaimLeaseSeconds
}

func (r Reminders) GetEnabled() bool {
	return r.Enabled
}

func (r Reminders) GetInitialDelayMinutes() int {
	return r.InitialDelayMinutes
}

func (r Reminders) GetIntervalMinutes() int {
	return r.IntervalMinutes
}

func (r Reminders) GetJitterPercent() int {
	return r.JitterPercent
}

func (r Reminders) GetManualResendCooldownMinutes() int {
	return r.ManualResendCooldownMinutes
}

func (r Reminders) GetMaxReminders() int {
	return r.MaxReminders
}

func (r Reminders) GetRecentViewGraceMinutes() int {
	return r.RecentViewGraceMinutes
}

func (r Reminders) GetRotateToken() bool {
	return r.RotateToken
}

func (r Reminders) GetSweepCron() string {
	return r.SweepCron
}

// Runtime Getters

func (r Runtime) GetProfile() string {
	return r.Profile
}

func (r Runtime) GetRepositoryDialect() string {
	return r.RepositoryDialect
}

func (r Runtime) GetStartupPolicy() string {
	return r.StartupPolicy
}

func (r Runtime) GetStrictStartup() bool {
	return r.StrictStartup
}

// SMTP Getters

func (s SMTP) GetDisableSTARTTLS() bool {
	return s.DisableSTARTTLS
}

func (s SMTP) GetFromAddress() string {
	return s.FromAddress
}

func (s SMTP) GetFromName() string {
	return s.FromName
}

func (s SMTP) GetHost() string {
	return s.Host
}

func (s SMTP) GetInsecureTLS() bool {
	return s.InsecureTLS
}

func (s SMTP) GetPassword() string {
	return s.Password
}

func (s SMTP) GetPort() int {
	return s.Port
}

func (s SMTP) GetTimeoutSeconds() int {
	return s.TimeoutSeconds
}

func (s SMTP) GetUsername() string {
	return s.Username
}

// Server Getters

func (s Server) GetAddress() string {
	return s.Address
}

// Services Getters

func (s Services) GetCallbackPublicBaseURL() string {
	return s.CallbackPublicBaseURL
}

func (s Services) GetEncryptionKey() string {
	return s.EncryptionKey
}

func (s Services) GetModuleEnabled() bool {
	return s.ModuleEnabled
}

// Signer Getters

func (s Signer) GetPDF() Pdf {
	return s.PDF
}

func (s Signer) GetProfileMode() string {
	return s.ProfileMode
}

func (s Signer) GetProfilePersistDrawnSignature() bool {
	return s.ProfilePersistDrawnSignature
}

func (s Signer) GetProfileTTLDays() int {
	return s.ProfileTTLDays
}

func (s Signer) GetSavedSignaturesLimitPerType() int {
	return s.SavedSignaturesLimitPerType
}

func (s Signer) GetUploadSigningKey() string {
	return s.UploadSigningKey
}

func (s Signer) GetUploadTTLSeconds() int {
	return s.UploadTTLSeconds
}

// SignerSession Getters

func (s SignerSession) GetMaxRequests() int {
	return s.MaxRequests
}

func (s SignerSession) GetWindowSeconds() int {
	return s.WindowSeconds
}

// Sqlite Getters

func (s Sqlite) GetDSN() string {
	return s.DSN
}

// Storage Getters

func (s Storage) GetBackend() string {
	return s.Backend
}

func (s Storage) GetEncryptionAlgorithm() string {
	return s.EncryptionAlgorithm
}

func (s Storage) GetFS() StorageFS {
	return s.FS
}

func (s Storage) GetKMSKeyID() string {
	return s.KMSKeyID
}

func (s Storage) GetS3() StorageS3 {
	return s.S3
}

// StorageFS Getters

func (s StorageFS) GetBasePath() string {
	return s.BasePath
}

// StorageS3 Getters

func (s StorageS3) GetAccessKeyID() string {
	return s.AccessKeyID
}

func (s StorageS3) GetBasePath() string {
	return s.BasePath
}

func (s StorageS3) GetBucket() string {
	return s.Bucket
}

func (s StorageS3) GetDisableSSL() bool {
	return s.DisableSSL
}

func (s StorageS3) GetEndpointURL() string {
	return s.EndpointURL
}

func (s StorageS3) GetProfile() string {
	return s.Profile
}

func (s StorageS3) GetRegion() string {
	return s.Region
}

func (s StorageS3) GetSecretAccessKey() string {
	return s.SecretAccessKey
}

func (s StorageS3) GetSessionToken() string {
	return s.SessionToken
}

func (s StorageS3) GetUsePathStyle() bool {
	return s.UsePathStyle
}
