app_config:
  - name: config_path
    override: ConfigPath
    type: string
    tags:
      json: "-"
      koanf: "-"

features:
  - name: overrides
    type: map[string]bool

server:
  - name: shutdown_timeout_seconds
    type: int
