// Code generated by config-getters; DO NOT EDIT.

package config

// AppConfig Getters

func (a AppConfig) GetAdmin() Admin {
	return a.Admin
}

func (a AppConfig) GetAuth() Auth {
	return a.Auth
}

func (a AppConfig) GetConfigPath() string {
	return a.ConfigPath
}

func (a AppConfig) GetDeployment() Deployment {
	return a.Deployment
}

func (a AppConfig) GetEnv() string {
	return a.Env
}

func (a AppConfig) GetFeatures() Features {
	return a.Features
}

func (a AppConfig) GetLogging() Logging {
	return a.Logging
}

func (a AppConfig) GetName() string {
	return a.Name
}

func (a AppConfig) GetServer() Server {
	return a.Server
}

// Admin Getters

func (a Admin) GetBasePath() string {
	return a.BasePath
}

func (a Admin) GetDefaultLocale() string {
	return a.DefaultLocale
}

func (a Admin) GetTitle() string {
	return a.Title
}

// Auth Getters

func (a Auth) GetDemoEmail() string {
	return a.DemoEmail
}

func (a Auth) GetDemoEnabled() bool {
	return a.DemoEnabled
}

func (a Auth) GetDemoPassword() string {
	return a.DemoPassword
}

func (a Auth) GetDemoUsername() string {
	return a.DemoUsername
}

func (a Auth) GetShowDemoCredentials() bool {
	return a.ShowDemoCredentials
}

func (a Auth) GetSigningKey() string {
	return a.SigningKey
}

// Deployment Getters

func (d Deployment) GetAppID() string {
	return d.AppID
}

func (d Deployment) GetAppName() string {
	return d.AppName
}

func (d Deployment) GetAppVersion() string {
	return d.AppVersion
}

func (d Deployment) GetPersonaEnabled() bool {
	return d.PersonaEnabled
}

// Features Getters

func (f Features) GetOverrides() map[string]bool {
	return f.Overrides
}

func (f Features) GetProfile() string {
	return f.Profile
}

// Logging Getters

func (l Logging) GetFormat() string {
	return l.Format
}

func (l Logging) GetLevel() string {
	return l.Level
}

// Server Getters

func (s Server) GetAddress() string {
	return s.Address
}

func (s Server) GetPrintRoutes() bool {
	return s.PrintRoutes
}

func (s Server) GetShutdownTimeoutSeconds() int {
	return s.ShutdownTimeoutSeconds
}
