// Code generated by app-config; DO NOT EDIT.

package config

type AppConfig struct {
	Admin      Admin    `json:"admin" koanf:"admin"`
	Auth       Auth     `json:"auth" koanf:"auth"`
	ConfigPath string   `json:"-" koanf:"-"`
	Env        string   `json:"env" koanf:"env"`
	Features   Features `json:"features" koanf:"features"`
	Name       string   `json:"name" koanf:"name"`
	Server     Server   `json:"server" koanf:"server"`
}

type Admin struct {
	BasePath      string `json:"base_path" koanf:"base_path"`
	DefaultLocale string `json:"default_locale" koanf:"default_locale"`
	Title         string `json:"title" koanf:"title"`
}

type Auth struct {
	DemoEmail    string `json:"demo_email" koanf:"demo_email"`
	DemoPassword string `json:"demo_password" koanf:"demo_password"`
	DemoUsername string `json:"demo_username" koanf:"demo_username"`
	SigningKey   string `json:"signing_key" koanf:"signing_key"`
}

type Features struct {
	CMS       bool `json:"cms" koanf:"cms"`
	Commands  bool `json:"commands" koanf:"commands"`
	Dashboard bool `json:"dashboard" koanf:"dashboard"`
	Jobs      bool `json:"jobs" koanf:"jobs"`
	Media     bool `json:"media" koanf:"media"`
	Search    bool `json:"search" koanf:"search"`
	Settings  bool `json:"settings" koanf:"settings"`
	Users     bool `json:"users" koanf:"users"`
}

type Server struct {
	Address     string `json:"address" koanf:"address"`
	PrintRoutes bool   `json:"print_routes" koanf:"print_routes"`
}
