// Code generated by app-config; DO NOT EDIT.

package config

type AppConfig struct {
	Admin      Admin      `json:"admin" koanf:"admin"`
	Auth       Auth       `json:"auth" koanf:"auth"`
	ConfigPath string     `json:"-" koanf:"-"`
	Deployment Deployment `json:"deployment" koanf:"deployment"`
	Env        string     `json:"env" koanf:"env"`
	Features   Features   `json:"features" koanf:"features"`
	Name       string     `json:"name" koanf:"name"`
	Server     Server     `json:"server" koanf:"server"`
}

type Admin struct {
	BasePath      string `json:"base_path" koanf:"base_path"`
	DefaultLocale string `json:"default_locale" koanf:"default_locale"`
	Title         string `json:"title" koanf:"title"`
}

type Auth struct {
	DemoEmail           string `json:"demo_email" koanf:"demo_email"`
	DemoEnabled         bool   `json:"demo_enabled" koanf:"demo_enabled"`
	DemoPassword        string `json:"demo_password" koanf:"demo_password"`
	DemoUsername        string `json:"demo_username" koanf:"demo_username"`
	ShowDemoCredentials bool   `json:"show_demo_credentials" koanf:"show_demo_credentials"`
	SigningKey          string `json:"signing_key" koanf:"signing_key"`
}

type Deployment struct {
	AppID          string `json:"app_id" koanf:"app_id"`
	AppName        string `json:"app_name" koanf:"app_name"`
	AppVersion     string `json:"app_version" koanf:"app_version"`
	PersonaEnabled bool   `json:"persona_enabled" koanf:"persona_enabled"`
}

type Features struct {
	Overrides map[string]bool `json:"overrides" koanf:"overrides"`
	Profile   string          `json:"profile" koanf:"profile"`
}

type Server struct {
	Address                string `json:"address" koanf:"address"`
	PrintRoutes            bool   `json:"print_routes" koanf:"print_routes"`
	ShutdownTimeoutSeconds int    `json:"shutdown_timeout_seconds" koanf:"shutdown_timeout_seconds"`
}
