// Code generated by config-getters; DO NOT EDIT.

package config

// AppConfig Getters

func (a AppConfig) GetAdmin() Admin {
	return a.Admin
}

func (a AppConfig) GetAuth() Auth {
	return a.Auth
}

func (a AppConfig) GetConfigPath() string {
	return a.ConfigPath
}

func (a AppConfig) GetEnv() string {
	return a.Env
}

func (a AppConfig) GetFeatures() Features {
	return a.Features
}

func (a AppConfig) GetName() string {
	return a.Name
}

func (a AppConfig) GetServer() Server {
	return a.Server
}

// Admin Getters

func (a Admin) GetBasePath() string {
	return a.BasePath
}

func (a Admin) GetDefaultLocale() string {
	return a.DefaultLocale
}

func (a Admin) GetTitle() string {
	return a.Title
}

// Auth Getters

func (a Auth) GetDemoEmail() string {
	return a.DemoEmail
}

func (a Auth) GetDemoPassword() string {
	return a.DemoPassword
}

func (a Auth) GetDemoUsername() string {
	return a.DemoUsername
}

func (a Auth) GetSigningKey() string {
	return a.SigningKey
}

// Features Getters

func (f Features) GetCMS() bool {
	return f.CMS
}

func (f Features) GetCommands() bool {
	return f.Commands
}

func (f Features) GetDashboard() bool {
	return f.Dashboard
}

func (f Features) GetJobs() bool {
	return f.Jobs
}

func (f Features) GetMedia() bool {
	return f.Media
}

func (f Features) GetSearch() bool {
	return f.Search
}

func (f Features) GetSettings() bool {
	return f.Settings
}

func (f Features) GetUsers() bool {
	return f.Users
}

// Server Getters

func (s Server) GetAddress() string {
	return s.Address
}

func (s Server) GetPrintRoutes() bool {
	return s.PrintRoutes
}
