/**
 * E-Sign Module
 * Main entry point for the e-sign frontend module
 *
 * This module provides TypeScript-based page controllers and utilities
 * for the e-sign application, replacing inline template JavaScript.
 */

// Types
export * from './types.js';
export {
  normalizeCandidateWarningSummary,
  normalizeLineagePresentationWarning,
  normalizeDocumentLineageDetail,
  normalizeAgreementLineageDetail,
  normalizeGoogleImportLineageStatus,
  normalizeGoogleImportRunHandle,
  normalizeGoogleImportRunDetail,
  isTerminalGoogleImportStatus,
  resolveGoogleImportRedirectURL,
  normalizePhase1LineageContractFixtures,
  // Fingerprint status constants (Phase 7 Task 7.7)
  FINGERPRINT_STATUS,
  isValidFingerprintStatus,
  // Candidate relationship constants (Phase 8 Task 8.9)
  CANDIDATE_RELATIONSHIP_STATUS,
  CANDIDATE_RELATIONSHIP_TYPE,
  CONFIDENCE_BAND,
  isValidCandidateRelationshipStatus,
  type FingerprintStatus,
  type CandidateRelationshipStatus,
  type CandidateRelationshipType,
  type ConfidenceBand,
  type GoogleImportRunHandle,
  type GoogleImportRunDetail,
  type GoogleImportRunResource,
  type GoogleImportRedirectRoutes,
  type LineagePresentationWarning,
} from './lineage-contracts.js';

// Lineage Presentation Mappers (Phase 5 Task 5.6)
export {
  mapDocumentProvenance,
  mapAgreementProvenance,
  validateDocumentProvenanceViewModel,
  validateAgreementProvenanceViewModel,
  isGoogleSourced,
  hasActionableWarnings,
  getWarningSeverityClass,
  getWarningSeverityIcon,
  getSourceTypeIcon,
  getSourceTypeLabel,
  // Fingerprint status helpers (Phase 7 Task 7.7)
  getFingerprintStatusClass,
  getFingerprintStatusIcon,
  isFingerprintTerminal,
  isFingerprintSuccessful,
  hasFingerprintError,
  getFingerprintStatusMessage,
  type ProvenanceSourceType,
  type ProvenanceStatus,
  type WarningSeverity,
  type ProvenanceWarning,
  type ProvenanceSourceReference,
  type ProvenanceRevisionSummary,
  type ProvenanceArtifactSummary,
  type ProvenanceFingerprintStatus,
  type ProvenanceGoogleSource,
  type ProvenanceEmptyState,
  type DocumentProvenanceViewModel,
  type AgreementProvenanceViewModel,
} from './lineage-presentation.js';

// Lineage Diagnostics Rendering (Phase 6 Task 6.6)
export {
  // State determination
  determineDiagnosticState,
  // Display config builders
  createEmptyDisplayConfig,
  createNativeDisplayConfig,
  createFingerprintPendingDisplayConfig,
  createFingerprintFailedDisplayConfig,
  createCandidateWarningDisplayConfig,
  createLoadingDisplayConfig,
  createErrorDisplayConfig,
  // Card builders
  createWarningCard,
  createWarningCards,
  createFingerprintCard,
  createSourceCard,
  createNewerSourceCard,
  // Complete view model builders
  createDocumentDiagnosticViewModel,
  createAgreementDiagnosticViewModel,
  // State checks
  isDiagnosticEmpty,
  isDiagnosticNative,
  isDiagnosticFingerprintPending,
  isDiagnosticFingerprintFailed,
  isDiagnosticCandidateWarning,
  getPrimaryWarningCard,
  hasDiagnosticActionableWarnings,
  // Validation
  validateDocumentDiagnosticViewModel,
  validateAgreementDiagnosticViewModel,
  // Types
  type DiagnosticRenderState,
  type DiagnosticDisplayConfig,
  type DiagnosticWarningCard,
  type DiagnosticFingerprintCard,
  type DiagnosticSourceCard,
  type DiagnosticNewerSourceCard,
  type DocumentDiagnosticViewModel,
  type AgreementDiagnosticViewModel,
  type DiagnosticFixtureState,
} from './lineage-diagnostics.js';

// Provenance Card Interactivity (Phase 9 Task 9.5-9.8)
export {
  // Initialization
  initProvenanceCards,
  bootstrapProvenanceCards,
  initAllEvidenceToggles,
  initEvidenceToggle,
  // Utilities
  getProvenanceCards,
  getProvenanceCardFor,
  hasWarnings,
  hasEmptyState,
  getLineageStatus,
  getResourceKind,
  // Constants
  PROVENANCE_CARD_SELECTOR,
  EVIDENCE_TOGGLE_SELECTOR,
  EVIDENCE_COLLAPSED_SELECTOR,
  EVIDENCE_CONTAINER_SELECTOR,
  DEFAULT_PROVENANCE_CARD_CONFIG,
  // Types
  type ProvenanceCardConfig,
} from './provenance-card.js';

// Lineage Fixtures (Phase 2 Task 2.7-2.9)
export {
  documentLineageFixtures,
  agreementLineageFixtures,
  getDocumentLineageFixture,
  getAgreementLineageFixture,
  validateDocumentLineagePayload,
  validateAgreementLineagePayload,
  type DocumentLineageFixtures,
  type AgreementLineageFixtures,
  type LineageFixtureState,
  // Phase 3 Task 3.10 - Import state fixtures
  importResponseFixtures,
  getImportResponseFixture,
  validateImportResponsePayload,
  getImportFixtureStates,
  type ImportResponseFixtures,
  type ImportFixtureState,
  // Phase 4 Task 4.9 - Document/Agreement detail payload fixtures with lineage
  documentDetailPayloadFixtures,
  agreementDetailPayloadFixtures,
  getDocumentDetailPayloadFixture,
  getAgreementDetailPayloadFixture,
  validateDocumentDetailPayloadWithLineage,
  validateAgreementDetailPayloadWithLineage,
  hasDocumentLineageLinkage,
  hasAgreementPinnedProvenance,
  getDetailPayloadFixtureStates,
  type DocumentDetailPayloadWithLineage,
  type AgreementDetailPayloadWithLineage,
  type DocumentDetailPayloadFixtures,
  type AgreementDetailPayloadFixtures,
  type DetailPayloadFixtureState,
  // Phase 4 Task 4.10 - Seeded Google import QA fixtures
  seededGoogleImportScenarios,
  getSeededGoogleImportScenario,
  getSeededScenarioIds,
  validateSeededScenarioLineage,
  type SeededGoogleImportScenario,
  // Phase 8 Task 8.9 - Candidate warning fixtures
  candidateWarningFixtures,
  agreementCandidateWarningFixtures,
  getCandidateWarningFixture,
  getAgreementCandidateWarningFixture,
  getCandidateWarningFixtureStates,
  isCandidateActionable,
  isCandidateResolved,
  getPrimaryCandidateWarning,
  countCandidatesByStatus,
  validateCandidateWarningFixture,
  type CandidateWarningFixtureState,
  type ExtendedCandidateWarningSummary,
  type CandidateWarningFixtures,
  type AgreementCandidateWarningFixtures,
} from './lineage-fixtures.js';

// Source-Management Contracts And Runtime (Phase 11-13)
export {
  normalizePhase13SourceSearchQuery,
  normalizePhase13SourceSearchResultSummary,
  normalizePhase13SourceSearchResults,
  normalizePhase13SourceCommentThreadSummary,
  normalizePhase13SourceCommentPage,
  normalizeSourceCommentAuthorSummary,
  normalizeSourceCommentMessageSummary,
  normalizeSourceCommentSyncSummary,
  COMMENT_SYNC_STATUS,
  SEARCH_RESULT_KIND,
  isValidCommentSyncStatus,
  type SourceManagementLinks,
  type SourceManagementPermissions,
  type SourceListPage,
  type SourceDetail,
  type SourceRevisionPage,
  type SourceRelationshipPage,
  type SourceHandlePage,
  type SourceRevisionDetail,
  type SourceArtifactPage,
  type SourceCommentPage,
  type SourceSearchResults,
  type SourceListQuery,
  type SourceRevisionListQuery,
  type SourceRelationshipListQuery,
  type SourceSearchQuery,
  type Phase13SourceSearchQuery,
  type Phase13SourceSearchResults,
  type Phase13SourceSearchResultSummary,
  type Phase13SourceCommentPage,
  type Phase13SourceCommentThreadSummary,
  type SourceCommentAuthorSummary,
  type SourceCommentMessageSummary,
  type SourceCommentSyncSummary,
  type SourceCommentListQuery,
  type Phase11SourceManagementContractFixtures,
  type Phase13SourceManagementContractFixtures,
} from './lineage-contracts.js';

export {
  SOURCE_LIST_EMPTY,
  SOURCE_LIST_SINGLE,
  SOURCE_DETAIL_REPEATED,
  SOURCE_DETAIL_MERGED,
  SOURCE_DETAIL_ARCHIVED,
  SOURCE_REVISIONS_REPEATED,
  SOURCE_RELATIONSHIPS_REVIEW,
  SEARCH_EMPTY,
  SEARCH_RESULTS_WITH_COMMENTS,
  COMMENTS_EMPTY,
  COMMENTS_SYNCED,
  COMMENTS_PENDING_SYNC,
  COMMENTS_SYNC_FAILED,
  COMMENTS_SYNC_STALE,
  PHASE_11_FIXTURES,
  PHASE_13_FIXTURES,
  createSourceListPageFixture,
  createSourceDetailFixture,
  createSourceRevisionPageFixture,
  createSourceRelationshipPageFixture,
  createPhase13SourceSearchResultsFixture,
  createPhase13SourceCommentPageFixture,
  PHASE_14_FIXTURE_ROUTES,
} from './source-management-fixtures.js';

export {
  adaptEmptyState,
  adaptPaginationInfo,
  adaptSourceListItem,
  adaptSourceDetail,
  adaptSourceRevisionListItem,
  adaptSourceRelationshipSummary,
  adaptSourceListPage,
  adaptSourceRevisionPage,
  adaptSourceRelationshipPage,
  type SourceListItemViewModel,
  type SourceDetailViewModel,
  type SourceRevisionListItemViewModel,
  type SourceRelationshipViewModel,
  type PaginationViewModel,
  type EmptyStateViewModel,
} from './source-management-adapters.js';

export {
  SourceBrowserPageController,
  SourceCommentInspectorPageController,
  SourceDetailPageController,
  SourceRevisionInspectorPageController,
  SourceRevisionTimelinePageController,
  SourceArtifactInspectorPageController,
  SourceSearchPageController,
  bootstrapSourceBrowserPage,
  bootstrapSourceCommentInspectorPage,
  bootstrapSourceDetailPage,
  bootstrapSourceRevisionInspectorPage,
  bootstrapSourceRevisionTimelinePage,
  bootstrapSourceArtifactInspectorPage,
  bootstrapSourceSearchPage,
  registerPageController,
  getPageController,
  listRegisteredPages,
  type SourceBrowserPageConfig,
  type SourceCommentInspectorPageConfig,
  type SourceDetailPageConfig,
  type SourceRevisionInspectorPageConfig,
  type SourceRevisionTimelinePageConfig,
  type SourceArtifactInspectorPageConfig,
  type SourceSearchPageConfig,
} from './source-management-pages.js';

export {
  SourceManagementRuntimeController,
  initSourceManagementRuntimePage,
  translateSourceManagementHrefToRuntime,
  resolveBrowserItemRuntimeHref,
  resolveSearchResultRuntimeHref,
  SOURCE_SEARCH_RESULT_KIND_OPTIONS,
  // Phase 18 V2 runtime initialization (Task 18.7)
  initV2SourceManagementRuntime,
  assertV2RuntimeInitialization,
  logV2RuntimeInitResult,
  type V2RuntimeInitResult,
} from './source-management-runtime.js';

export {
  createLoadingState,
  createEmptyState,
  createErrorState,
  createUnauthorizedState,
  createDegradedState,
  resolveSourceListRenderingState,
  resolveSourceDetailRenderingState,
  resolveSourceRevisionTimelineRenderingState,
  adaptPhase13SearchResult,
  adaptCommentSyncStatus,
  adaptPhase13CommentThread,
  createPhase13SearchSuccessState,
  createPhase13CommentSuccessState,
  resolvePhase13SearchRenderingState,
  resolvePhase13CommentRenderingState,
  type PageRenderingStateKind,
  type RenderingStateMetadata,
  type LoadingStateViewModel,
  type EmptyStateViewModel2,
  type PartialDataStateViewModel,
  type ErrorStateViewModel,
  type UnauthorizedStateViewModel,
  type DegradedStateViewModel,
  type Phase13SearchResultViewModel,
  type CommentSyncStatusViewModel,
  type Phase13CommentThreadViewModel,
  type Phase13SearchSuccessStateViewModel,
  type Phase13CommentSuccessStateViewModel,
  type Phase13SearchRenderingState,
  type Phase13CommentRenderingState,
} from './source-management-rendering-states.js';

export {
  isDocumentLineageDetail,
  isAgreementLineageDetail,
  isSourceManagementContract,
  isPhase13SourceSearchResults,
  isPhase13SourceCommentPage,
  isAgreementReviewCommentPayload,
  isRawGoogleDriveCommentPayload,
  checkCompositionBoundaryViolation,
  checkAdapterBoundaryViolation,
  checkSemanticComputationViolation,
  checkEndpointStitchingViolation,
  checkSourceCommentMixingViolation,
  checkGoogleProviderPayloadViolation,
  checkSearchContractViolation,
  checkCommentContractViolation,
  checkContractModuleConsumptionViolation,
  checkRawGoogleFieldAccessViolation,
  checkCanonicalContractFamilyViolation,
  checkSemanticOwnershipViolation,
  runPageGuards,
  runPhase13PageGuards,
  runPhase14PageGuards,
  assertPageGuards,
  assertPhase13PageGuards,
  assertPhase14PageGuards,
  setGuardEnforcementMode,
  getGuardEnforcementMode,
  createMockAgreementReviewComment,
  createMockRawGoogleDriveComment,
  createMockPhase13SourceCommentPage,
  createMockPhase13SearchResults,
  createPassingPhase14PageConfig,
  createPhase14SurfacePageConfig,
  createModuleViolationConfig,
  createGoogleFieldViolationConfig,
  createMultipleContractFamilyViolationConfig,
  createSemanticOwnershipViolationConfig,
  PHASE_14_APPROVED_CONTRACT_MODULES,
  FORBIDDEN_RAW_GOOGLE_FIELDS,
  APPROVED_GOOGLE_ADAPTER_BOUNDARIES,
  PHASE_14_GUARD_SURFACES,
  PHASE_14_SURFACE_PAGE_IDS,
  PHASE_14_SURFACE_ENDPOINT_FALLBACKS,
  PHASE_14_ARCHITECTURAL_INVARIANTS,
  type GuardViolationResult,
  type GuardEnforcementMode,
  type PageGuardConfig,
  type PageGuardResult,
  type Phase13PageGuardConfig,
  type Phase14PageGuardConfig,
  type Phase14GuardSurface,
  type Phase14RawFieldAccess,
  type Phase14RawFieldAccessInput,
} from './source-management-guards.js';

export {
  createSourceDetailWorkspace,
  createSourceSearchWorkspace,
  validatePageComposition,
  detectProvenancePayloadMixing,
  SOURCE_MANAGEMENT_COMPOSITION_GUIDELINES,
  PHASE_13_COMPOSITION_GUIDELINES,
  VERSION_2_ARCHITECTURAL_INVARIANTS,
  type SourceBrowserPageContracts,
  type SourceDetailPageContracts,
  type SourceRevisionTimelinePageContracts,
  type SourceRelationshipGraphPageContracts,
  type SourceHandleHistoryPageContracts,
  type SourceRevisionDetailPageContracts,
  type SourceArtifactInspectorPageContracts,
  type SourceCommentInspectorPageContracts,
  type SourceSearchPageContracts,
  type Phase13SourceSearchWorkspaceContracts,
  type Phase13SourceCommentWorkspaceContracts,
  type SourceManagementWorkspaceOrchestration,
  type SourceDetailWorkspacePanels,
  type SourceSearchWorkspacePanels,
  type SourceManagementPageState,
  type SourceManagementPageMetadata,
  type PageCompositionGuardResult,
} from './source-management-composition.js';

export {
  V2_LANDING_ZONE_SURFACES,
  SURFACE_CONTRACT_MAPPING,
  V2_FIXTURE_ROUTES,
  loadFixtureForSurface,
  smokeTestSourceList,
  smokeTestSourceDetail,
  smokeTestRevisionHistory,
  smokeTestRelationshipSummaries,
  smokeTestSearch,
  smokeTestSourceComment,
  runV2LandingZoneSmokeTests,
  assertV2LandingZoneSmokeTests,
  smokeTestLoadingStates,
  smokeTestEmptyStates,
  smokeTestErrorStates,
  runComprehensiveSmokeCoverage,
  validateFixtureRoutes,
  logSmokeTestResults,
  // Phase 15 runtime page bootstrap smoke tests
  PHASE_15_PAGE_DEFINITIONS,
  runPhase15PageBootstrapSmokeTests,
  assertPhase15PageBootstrapSmokeTests,
  validateLivePageBootstrap,
  logPhase15SmokeTestResults,
  runPhase15RuntimeSmokeCoverage,
  // Phase 16 workspace smoke tests
  runPhase16WorkspaceSmokeTests,
  assertPhase16WorkspaceSmokeTests,
  runPhase16RuntimeSmokeCoverage,
  logPhase16SmokeTestResults,
  runPhase16ComprehensiveSmokeCoverage,
  // Phase 17 reconciliation queue smoke tests
  runPhase17ReconciliationQueueSmokeTests,
  assertPhase17ReconciliationQueueSmokeTests,
  logPhase17SmokeTestResults,
  runPhase17ComprehensiveSmokeCoverage,
  // Phase 18 V2 operator journey smoke tests
  V2_OPERATOR_JOURNEY_STEPS,
  runPhase18V2JourneySmokeTests,
  assertPhase18V2JourneySmokeTests,
  logPhase18SmokeTestResults,
  runPhase18ComprehensiveSmokeCoverage,
  assertPhase18ComprehensiveSmokeCoverage,
  runV2ExitCriteriaValidation,
  logV2ExitCriteriaResults,
  type SmokeTestRuntimeOptions,
  type FixtureRouteValidationResult,
  type SmokeSurfaceResult,
  type V2LandingZoneSmokeResult,
  type V2LandingZoneSurface,
  type Phase15PageBootstrapResult,
  type Phase15RuntimeSmokeResult,
  type Phase15PageId,
  type Phase16WorkspacePanelResult,
  type Phase16WorkspaceSmokeResult,
  type Phase17QueueSmokeTestResult,
  type Phase17ReconciliationQueueSmokeResult,
  type Phase18JourneyStep,
  type Phase18JourneyStepResult,
  type Phase18V2JourneySmokeResult,
} from './source-management-smoke-tests.js';

// Source Detail Workspace (Phase 16)
export {
  // Workspace Composition
  createInitialWorkspaceState,
  createLoadingWorkspaceState,
  updateWorkspacePanel,
  setActivePanel,
  getPanelDrillInUrl,
  panelRequiresLoad,
  // Panel State Resolvers
  resolveOverviewPanelState,
  resolveRevisionsPanelState,
  resolveArtifactsPanelState,
  resolveRelationshipsPanelState,
  resolveCommentsPanelState,
  resolveHandlesPanelState,
  // Panel State Creators
  createPanelLoadingState,
  createPanelErrorState,
  createPanelEmptyState,
  createOverviewPanelSuccessState,
  createRevisionsPanelSuccessState,
  createArtifactsPanelSuccessState,
  createRelationshipsPanelSuccessState,
  createCommentsPanelSuccessState,
  createHandlesPanelSuccessState,
  // Contract Validation
  validateWorkspaceContractUsage,
  validateWorkspaceContractIsolation,
  validateWorkspaceBackendLinks,
  WORKSPACE_APPROVED_CONTRACT_FAMILIES,
  WORKSPACE_FORBIDDEN_CONTRACT_FAMILIES,
  // Types
  type SourceWorkspacePanel,
  type WorkspacePanelStateKind,
  type WorkspacePanelMetadata,
  type WorkspacePanelLoadingState,
  type WorkspacePanelEmptyState,
  type WorkspacePanelErrorState,
  type OverviewPanelSuccessState,
  type RevisionsPanelSuccessState,
  type ArtifactsPanelSuccessState,
  type RelationshipsPanelSuccessState,
  type CommentsPanelSuccessState,
  type HandlesPanelSuccessState,
  type ArtifactPanelItemViewModel,
  type CommentPanelItemViewModel,
  type HandlePanelItemViewModel,
  type OverviewPanelRenderingState,
  type RevisionsPanelRenderingState,
  type ArtifactsPanelRenderingState,
  type RelationshipsPanelRenderingState,
  type CommentsPanelRenderingState,
  type HandlesPanelRenderingState,
  type SourceDetailWorkspaceState,
  type WorkspaceContractFamily,
  type WorkspaceContractValidationResult,
} from './source-detail-workspace.js';

// API Client
export {
  ESignAPIClient,
  ESignAPIError,
  getESignClient,
  setESignClient,
  createESignClient,
  type ESignAPIClientConfig,
} from './api-client.js';

// Utilities
export {
  // Formatters
  formatFileSize,
  formatPageCount,
  formatDateTime,
  formatDate,
  formatTime,
  formatRelativeTime,
  formatRecipientCount,
  capitalize,
  snakeToTitle,
  truncate,
  // Status badges
  AGREEMENT_STATUS_BADGES,
  getAgreementStatusBadge,
  renderStatusBadge,
  createStatusBadgeElement,
  updateStatusBadge,
  type BadgeConfig,
  // DOM helpers
  qs,
  qsa,
  byId,
  createElement,
  on,
  delegate,
  onReady,
  show,
  hide,
  toggle,
  setLoading,
  updateDataText,
  updateDataTexts,
  getPageConfig,
  announce,
  // Async helpers
  poll,
  retry,
  sleep,
  debounce,
  throttle,
  createTimeoutController,
  withTimeout,
  type PollOptions,
  type PollResult,
  type RetryOptions,
} from './utils/index.js';

// Page controllers
export {
  LandingPageController,
  initLandingPage,
  bootstrapLandingPage,
  type LandingPageConfig,
  SignerCompletePageController,
  initSignerCompletePage,
  bootstrapSignerCompletePage,
  type SignerCompleteConfig,
  type ArtifactUrls,
  type SignerCompletePayloadState,
  resolveSignerCompleteArtifacts,
  resolveSignerCompletePayloadState,
  getSignerCompletionPollDelayMs,
  formatSizeElements,
  formatTimestampElements,
  applyDetailFormatters,
  initDetailFormatters,
  // Google integration
  GoogleCallbackController,
  initGoogleCallback,
  bootstrapGoogleCallback,
  type GoogleCallbackConfig,
  GoogleIntegrationController,
  initGoogleIntegration,
  bootstrapGoogleIntegration,
  GoogleDrivePickerController,
  initGoogleDrivePicker,
  bootstrapGoogleDrivePicker,
  type GoogleDrivePickerConfig,
  // Integration pages
  IntegrationHealthController,
  initIntegrationHealth,
  bootstrapIntegrationHealth,
  type IntegrationHealthConfig,
  IntegrationMappingsController,
  initIntegrationMappings,
  bootstrapIntegrationMappings,
  type IntegrationMappingsConfig,
  IntegrationConflictsController,
  initIntegrationConflicts,
  bootstrapIntegrationConflicts,
  type IntegrationConflictsConfig,
  IntegrationSyncRunsController,
  initIntegrationSyncRuns,
  bootstrapIntegrationSyncRuns,
  type IntegrationSyncRunsConfig,
  // Document form
  DocumentFormController,
  initDocumentForm,
  bootstrapDocumentForm,
  type DocumentFormConfig,
  // Agreement form
  AgreementFormController,
  initAgreementForm,
  bootstrapAgreementForm,
  type AgreementFormConfig,
  // Signer review
  SignerReviewController,
  initSignerReview,
  bootstrapSignerReview,
  type SignerReviewConfig,
  // Signer error
  SignerErrorPageController,
  initSignerErrorPage,
  bootstrapSignerErrorPage,
  type SignerErrorConfig,
  // Document detail preview
  DocumentDetailPreviewController,
  initDocumentDetailPreview,
  bootstrapDocumentDetailPreview,
  type DocumentDetailPreviewConfig,
  // Agreement detail page controller
  AgreementDetailPageController,
  initAgreementDetailPage,
  bootstrapAgreementDetailPage,
  getAgreementDetailController,
  formatTimestamp,
  formatTimestampNodes,
  wireCollapsibleSections,
  reviewActorKey,
  reviewActorInfo,
  applyReviewActorMetadata,
  findParticipantById,
  safeParseJSONScript,
  looksLikeUUID,
  // Datatable bootstrap utilities
  PanelPaginationBehavior,
  PanelSearchBehavior,
  normalizeFilterType,
  normalizeFilterOptions,
  normalizeFilterOperators,
  prepareGridColumns,
  prepareFilterFields,
  dateTimeCellRenderer,
  fileSizeCellRenderer,
  defaultActionSuccessHandler,
  defaultActionErrorHandler,
  setupRefreshButton,
  createSchemaActionCachingRefresh,
  STANDARD_GRID_SELECTORS,
  type FilterField,
  type ColumnConfig,
  type CellRenderer,
  type DatatableBootstrapConfig,
} from './pages/index.js';

// Inline Status module (agreement detail live feedback)
export {
  // Manager
  InlineStatusManager,
  createInlineStatusManager,
  // Target resolution
  resolveStatusTarget,
  commandToSection,
  // Rendering
  createStatusElement,
  updateStatusElement,
  removeStatusElement,
  clearAllStatusElements,
  clearStaleStatusElements,
  // Command message customization
  getCommandMessage,
  COMMAND_MESSAGES,
  // Constants
  DEFAULT_INLINE_STATUS_CONFIG,
  SECTION_TARGET_SELECTORS,
  SECTION_FALLBACK_SELECTORS,
  PAGE_STATUS_TARGET,
  STATUS_DISPLAY,
  // Types
  type InlineStatusConfig,
  type StatusDisplayConfig,
  type StatusTargetResult,
  type CommandMessageConfig,
} from './inline-status.js';

// Timeline module
export {
  // Event registry
  TIMELINE_COLOR_CLASSES,
  DEFAULT_EVENT_CONFIG,
  EVENT_REGISTRY,
  CONDENSED_MODE_PRIORITY_THRESHOLD,
  getEventConfig,
  generateFallbackLabel,
  getColorClasses,
  isVisibleInCondensedMode,
  isGroupableEvent,
  // Event resolver
  buildActorKey,
  humanizeActorRole,
  getActorColor,
  getActorInitials,
  createResolverContext,
  resolveActor,
  resolveMetadata,
  resolveFieldLabel,
  resolveParticipantName,
  // Event grouper
  processEventsForDisplay,
  groupItemsByDate,
  countHiddenEvents,
  getDateLabel,
  renderTimeline,
  renderFilteredState,
  // Timeline controller
  TimelineController,
  createTimelineController,
  parseTimelineBootstrap,
  parseMergedTimelineBootstrap,
  mergeReviewDataIntoTimeline,
  mergeReviewBootstrapIntoTimeline,
  // Types
  type EventResolverContext,
  type ProcessedTimelineItem,
  type DateGroup,
  type FilterStats,
} from './timeline/index.js';

// Google Drive utilities
export {
  // Constants
  MIME_GOOGLE_DOC,
  MIME_GOOGLE_SHEET,
  MIME_GOOGLE_SLIDES,
  MIME_GOOGLE_FOLDER,
  MIME_PDF,
  IMPORTABLE_MIME_TYPES,
  GOOGLE_ACCOUNT_STORAGE_KEY,
  // Type predicates
  isGoogleDoc,
  isPDF,
  isFolder,
  isImportable,
  isGoogleWorkspaceFile,
  // Normalizers
  normalizeDriveFile,
  normalizeDriveFiles,
  // Display utilities
  getFileTypeName,
  getFileIconConfig,
  formatFileSize as formatDriveFileSize,
  formatDate as formatDriveDate,
  // Account ID management
  resolveAccountId,
  normalizeAccountId,
  saveAccountId,
  applyAccountIdToPath,
  buildScopedApiUrl,
  syncAccountIdToUrl,
  // HTML utilities
  escapeHtml,
  renderFileIcon,
  renderBreadcrumb,
  renderFileItem,
  renderFileList,
  createSelectedFile,
  // Types
  type NormalizedDriveFile,
  type FolderPathItem,
  type RawGoogleDriveFile,
  type SelectedFile,
} from './utils/google-drive-utils.js';
