// Code generated by go run ../../tools/facadegen; DO NOT EDIT.
// Source of truth: exported API surface from github.com/goliatone/go-admin/admin.

package admin

import (
	"context"
	core "github.com/goliatone/go-admin/admin"
	auth "github.com/goliatone/go-auth"
	cms "github.com/goliatone/go-cms"
	command "github.com/goliatone/go-command"
	"github.com/goliatone/go-command/dispatcher"
	"github.com/goliatone/go-command/runner"
	crud "github.com/goliatone/go-crud"
	"github.com/goliatone/go-crud/gql/registrar"
	errors "github.com/goliatone/go-errors"
	"github.com/goliatone/go-formgen/pkg/orchestrator"
	"github.com/goliatone/go-formgen/pkg/renderers/vanilla/components"
	repository "github.com/goliatone/go-repository-bun"
	router "github.com/goliatone/go-router"
	urlkit "github.com/goliatone/go-urlkit"
	"github.com/goliatone/go-users/activity"
	"github.com/goliatone/go-users/pkg/types"
	"github.com/uptrace/bun"
	"io/fs"
	"log/slog"
	"time"
)

const (
	ActionDisabledReasonCodeFeatureDisabled      = core.ActionDisabledReasonCodeFeatureDisabled
	ActionDisabledReasonCodeInvalidStatus        = core.ActionDisabledReasonCodeInvalidStatus
	ActionDisabledReasonCodeMissingContext       = core.ActionDisabledReasonCodeMissingContext
	ActionDisabledReasonCodePermissionDenied     = core.ActionDisabledReasonCodePermissionDenied
	ActionDisabledReasonCodeTranslationMissing   = core.ActionDisabledReasonCodeTranslationMissing
	ActionScopeAny                               = core.ActionScopeAny
	ActionScopeBulk                              = core.ActionScopeBulk
	ActionScopeDetail                            = core.ActionScopeDetail
	ActionScopeRow                               = core.ActionScopeRow
	ActivityActorTypeJob                         = core.ActivityActorTypeJob
	ActivityActorTypeKey                         = core.ActivityActorTypeKey
	ActivityActorTypeKeyLegacy                   = core.ActivityActorTypeKeyLegacy
	ActivityActorTypeSystem                      = core.ActivityActorTypeSystem
	ActivityActorTypeTask                        = core.ActivityActorTypeTask
	ActivityActorTypeUser                        = core.ActivityActorTypeUser
	ActivityObjectTypeBlock                      = core.ActivityObjectTypeBlock
	ActivityObjectTypeBlockDefinition            = core.ActivityObjectTypeBlockDefinition
	ActivityObjectTypeContent                    = core.ActivityObjectTypeContent
	ActivityObjectTypeDashboard                  = core.ActivityObjectTypeDashboard
	ActivityObjectTypeJob                        = core.ActivityObjectTypeJob
	ActivityObjectTypeMenu                       = core.ActivityObjectTypeMenu
	ActivityObjectTypeMenuItem                   = core.ActivityObjectTypeMenuItem
	ActivityObjectTypeNotification               = core.ActivityObjectTypeNotification
	ActivityObjectTypeOrganization               = core.ActivityObjectTypeOrganization
	ActivityObjectTypePage                       = core.ActivityObjectTypePage
	ActivityObjectTypePanel                      = core.ActivityObjectTypePanel
	ActivityObjectTypePreferences                = core.ActivityObjectTypePreferences
	ActivityObjectTypeProfile                    = core.ActivityObjectTypeProfile
	ActivityObjectTypeRole                       = core.ActivityObjectTypeRole
	ActivityObjectTypeSettings                   = core.ActivityObjectTypeSettings
	ActivityObjectTypeTenant                     = core.ActivityObjectTypeTenant
	ActivityObjectTypeUser                       = core.ActivityObjectTypeUser
	ActivityObjectTypeWidgetArea                 = core.ActivityObjectTypeWidgetArea
	ActivityObjectTypeWidgetDefinition           = core.ActivityObjectTypeWidgetDefinition
	ActivityObjectTypeWidgetInstance             = core.ActivityObjectTypeWidgetInstance
	AssignmentStatusApproved                     = core.AssignmentStatusApproved
	AssignmentStatusArchived                     = core.AssignmentStatusArchived
	AssignmentStatusAssigned                     = core.AssignmentStatusAssigned
	AssignmentStatusInProgress                   = core.AssignmentStatusInProgress
	AssignmentStatusPending                      = core.AssignmentStatusPending
	AssignmentStatusPublished                    = core.AssignmentStatusPublished
	AssignmentStatusRejected                     = core.AssignmentStatusRejected
	AssignmentStatusReview                       = core.AssignmentStatusReview
	AssignmentTypeDirect                         = core.AssignmentTypeDirect
	AssignmentTypeOpenPool                       = core.AssignmentTypeOpenPool
	CreateRoleOperation                          = core.CreateRoleOperation
	CreateTranslationKey                         = core.CreateTranslationKey
	DebugLayoutAdmin                             = core.DebugLayoutAdmin
	DebugLayoutStandalone                        = core.DebugLayoutStandalone
	DebugPanelConfig                             = core.DebugPanelConfig
	DebugPanelConsole                            = core.DebugPanelConsole
	DebugPanelCustom                             = core.DebugPanelCustom
	DebugPanelDoctor                             = core.DebugPanelDoctor
	DebugPanelJSErrors                           = core.DebugPanelJSErrors
	DebugPanelLogs                               = core.DebugPanelLogs
	DebugPanelPermissions                        = core.DebugPanelPermissions
	DebugPanelRequests                           = core.DebugPanelRequests
	DebugPanelRoutes                             = core.DebugPanelRoutes
	DebugPanelSQL                                = core.DebugPanelSQL
	DebugPanelSession                            = core.DebugPanelSession
	DebugPanelShell                              = core.DebugPanelShell
	DebugPanelTemplate                           = core.DebugPanelTemplate
	DebugREPLKindApp                             = core.DebugREPLKindApp
	DebugREPLKindShell                           = core.DebugREPLKindShell
	DebugREPLOverrideKeyMetadata                 = core.DebugREPLOverrideKeyMetadata
	DebugREPLOverrideTokenMetadata               = core.DebugREPLOverrideTokenMetadata
	DefaultIconLibrary                           = core.DefaultIconLibrary
	DefaultPreviewHTMLMaxSizeBytes               = core.DefaultPreviewHTMLMaxSizeBytes
	DefaultSchemaMaxDepth                        = core.DefaultSchemaMaxDepth
	DefaultSchemaMaxFields                       = core.DefaultSchemaMaxFields
	DefaultSchemaMaxSizeBytes                    = core.DefaultSchemaMaxSizeBytes
	DefaultUISchemaMaxSizeBytes                  = core.DefaultUISchemaMaxSizeBytes
	DoctorSeverityError                          = core.DoctorSeverityError
	DoctorSeverityInfo                           = core.DoctorSeverityInfo
	DoctorSeverityOK                             = core.DoctorSeverityOK
	DoctorSeverityWarn                           = core.DoctorSeverityWarn
	FeatureActivity                              = core.FeatureActivity
	FeatureBulk                                  = core.FeatureBulk
	FeatureCMS                                   = core.FeatureCMS
	FeatureCommands                              = core.FeatureCommands
	FeatureDashboard                             = core.FeatureDashboard
	FeatureExport                                = core.FeatureExport
	FeatureJobs                                  = core.FeatureJobs
	FeatureMedia                                 = core.FeatureMedia
	FeatureNotifications                         = core.FeatureNotifications
	FeatureOrganizations                         = core.FeatureOrganizations
	FeaturePreferences                           = core.FeaturePreferences
	FeaturePreview                               = core.FeaturePreview
	FeatureProfile                               = core.FeatureProfile
	FeatureSearch                                = core.FeatureSearch
	FeatureSettings                              = core.FeatureSettings
	FeatureTenants                               = core.FeatureTenants
	FeatureTranslationExchange                   = core.FeatureTranslationExchange
	FeatureTranslationQueue                      = core.FeatureTranslationQueue
	FeatureUsers                                 = core.FeatureUsers
	IconRenderModeCSS                            = core.IconRenderModeCSS
	IconRenderModeImg                            = core.IconRenderModeImg
	IconRenderModeSVG                            = core.IconRenderModeSVG
	IconRenderModeSpan                           = core.IconRenderModeSpan
	IconRenderModeUnknown                        = core.IconRenderModeUnknown
	IconTypeEmoji                                = core.IconTypeEmoji
	IconTypeLibrary                              = core.IconTypeLibrary
	IconTypeSVG                                  = core.IconTypeSVG
	IconTypeURL                                  = core.IconTypeURL
	IconTypeUnknown                              = core.IconTypeUnknown
	MenuItemTypeGroup                            = core.MenuItemTypeGroup
	MenuItemTypeItem                             = core.MenuItemTypeItem
	MenuItemTypeSeparator                        = core.MenuItemTypeSeparator
	ModuleStartupPolicyEnforce                   = core.ModuleStartupPolicyEnforce
	ModuleStartupPolicyWarn                      = core.ModuleStartupPolicyWarn
	NotificationMarkCommandName                  = core.NotificationMarkCommandName
	PanelEntryModeDetailCurrentUser              = core.PanelEntryModeDetailCurrentUser
	PanelEntryModeList                           = core.PanelEntryModeList
	PanelTabScopeDetail                          = core.PanelTabScopeDetail
	PanelTabScopeForm                            = core.PanelTabScopeForm
	PanelTabScopeList                            = core.PanelTabScopeList
	PanelUIRouteModeCanonical                    = core.PanelUIRouteModeCanonical
	PanelUIRouteModeCustom                       = core.PanelUIRouteModeCustom
	PermAdminTranslationsApprove                 = core.PermAdminTranslationsApprove
	PermAdminTranslationsAssign                  = core.PermAdminTranslationsAssign
	PermAdminTranslationsClaim                   = core.PermAdminTranslationsClaim
	PermAdminTranslationsEdit                    = core.PermAdminTranslationsEdit
	PermAdminTranslationsExport                  = core.PermAdminTranslationsExport
	PermAdminTranslationsImportApply             = core.PermAdminTranslationsImportApply
	PermAdminTranslationsImportValidate          = core.PermAdminTranslationsImportValidate
	PermAdminTranslationsImportView              = core.PermAdminTranslationsImportView
	PermAdminTranslationsManage                  = core.PermAdminTranslationsManage
	PermAdminTranslationsView                    = core.PermAdminTranslationsView
	PreferenceLevelOrg                           = core.PreferenceLevelOrg
	PreferenceLevelSystem                        = core.PreferenceLevelSystem
	PreferenceLevelTenant                        = core.PreferenceLevelTenant
	PreferenceLevelUser                          = core.PreferenceLevelUser
	PriorityHigh                                 = core.PriorityHigh
	PriorityLow                                  = core.PriorityLow
	PriorityNormal                               = core.PriorityNormal
	PriorityUrgent                               = core.PriorityUrgent
	RequiredFieldsValidationError                = core.RequiredFieldsValidationError
	RequiredFieldsValidationIgnore               = core.RequiredFieldsValidationIgnore
	RequiredFieldsValidationWarn                 = core.RequiredFieldsValidationWarn
	RolesOpenAPISource                           = core.RolesOpenAPISource
	SchemaFormatJSONSchema                       = core.SchemaFormatJSONSchema
	SchemaFormatOpenAPI                          = core.SchemaFormatOpenAPI
	SettingsScopeDefault                         = core.SettingsScopeDefault
	SettingsScopeSite                            = core.SettingsScopeSite
	SettingsScopeSystem                          = core.SettingsScopeSystem
	SettingsScopeUser                            = core.SettingsScopeUser
	TextCodeActivityActorContextInvalid          = core.TextCodeActivityActorContextInvalid
	TextCodeAutosaveConflict                     = core.TextCodeAutosaveConflict
	TextCodeClearKeysNotSupported                = core.TextCodeClearKeysNotSupported
	TextCodeConflict                             = core.TextCodeConflict
	TextCodeContentTypeSchemaBreaking            = core.TextCodeContentTypeSchemaBreaking
	TextCodeFeatureAliasDisabled                 = core.TextCodeFeatureAliasDisabled
	TextCodeFeatureDisabled                      = core.TextCodeFeatureDisabled
	TextCodeFeatureEnabledRequired               = core.TextCodeFeatureEnabledRequired
	TextCodeForbidden                            = core.TextCodeForbidden
	TextCodeInvalidFeatureConfig                 = core.TextCodeInvalidFeatureConfig
	TextCodeMissingPanel                         = core.TextCodeMissingPanel
	TextCodeNotFound                             = core.TextCodeNotFound
	TextCodePathConflict                         = core.TextCodePathConflict
	TextCodeRawUINotSupported                    = core.TextCodeRawUINotSupported
	TextCodeReplAppDisabled                      = core.TextCodeReplAppDisabled
	TextCodeReplDebugDisabled                    = core.TextCodeReplDebugDisabled
	TextCodeReplDisabled                         = core.TextCodeReplDisabled
	TextCodeReplExecPermissionDenied             = core.TextCodeReplExecPermissionDenied
	TextCodeReplIPDenied                         = core.TextCodeReplIPDenied
	TextCodeReplOverrideDenied                   = core.TextCodeReplOverrideDenied
	TextCodeReplPermissionDenied                 = core.TextCodeReplPermissionDenied
	TextCodeReplReadOnly                         = core.TextCodeReplReadOnly
	TextCodeReplRoleDenied                       = core.TextCodeReplRoleDenied
	TextCodeReplSessionLimit                     = core.TextCodeReplSessionLimit
	TextCodeReplShellDisabled                    = core.TextCodeReplShellDisabled
	TextCodeServiceUnavailable                   = core.TextCodeServiceUnavailable
	TextCodeTranslationExchangeInvalidPayload    = core.TextCodeTranslationExchangeInvalidPayload
	TextCodeTranslationExchangeMissingLinkage    = core.TextCodeTranslationExchangeMissingLinkage
	TextCodeTranslationExchangeStaleSourceHash   = core.TextCodeTranslationExchangeStaleSourceHash
	TextCodeTranslationExchangeUnsupportedFormat = core.TextCodeTranslationExchangeUnsupportedFormat
	TextCodeTranslationExists                    = core.TextCodeTranslationExists
	TextCodeTranslationMissing                   = core.TextCodeTranslationMissing
	TextCodeTranslationQueueConflict             = core.TextCodeTranslationQueueConflict
	TextCodeTranslationQueueVersionConflict      = core.TextCodeTranslationQueueVersionConflict
	TextCodeValidationError                      = core.TextCodeValidationError
	TextCodeWorkflowInvalidTransition            = core.TextCodeWorkflowInvalidTransition
	TextCodeWorkflowNotFound                     = core.TextCodeWorkflowNotFound
	UpdateRoleOperation                          = core.UpdateRoleOperation
	WorkflowBindingScopeContentType              = core.WorkflowBindingScopeContentType
	WorkflowBindingScopeGlobal                   = core.WorkflowBindingScopeGlobal
	WorkflowBindingScopeTrait                    = core.WorkflowBindingScopeTrait
	WorkflowBindingStatusActive                  = core.WorkflowBindingStatusActive
	WorkflowBindingStatusInactive                = core.WorkflowBindingStatusInactive
	WorkflowStatusActive                         = core.WorkflowStatusActive
	WorkflowStatusDeprecated                     = core.WorkflowStatusDeprecated
	WorkflowStatusDraft                          = core.WorkflowStatusDraft
)

var (
	ErrAutosaveConflict                     = core.ErrAutosaveConflict
	ErrFeatureDisabled                      = core.ErrFeatureDisabled
	ErrForbidden                            = core.ErrForbidden
	ErrInvalidDependencies                  = core.ErrInvalidDependencies
	ErrInvalidFeatureConfig                 = core.ErrInvalidFeatureConfig
	ErrMenuSlugConflict                     = core.ErrMenuSlugConflict
	ErrMissingTranslations                  = core.ErrMissingTranslations
	ErrNotFound                             = core.ErrNotFound
	ErrPathConflict                         = core.ErrPathConflict
	ErrPreferencesPathInvalid               = core.ErrPreferencesPathInvalid
	ErrPreferencesScopeMetadataInvalid      = core.ErrPreferencesScopeMetadataInvalid
	ErrPreferencesStoreRequired             = core.ErrPreferencesStoreRequired
	ErrREPLSessionLimit                     = core.ErrREPLSessionLimit
	ErrTranslationAlreadyExists             = core.ErrTranslationAlreadyExists
	ErrTranslationAssignmentConflict        = core.ErrTranslationAssignmentConflict
	ErrTranslationAssignmentVersionConflict = core.ErrTranslationAssignmentVersionConflict
	ErrTranslationCreateUnsupported         = core.ErrTranslationCreateUnsupported
	ErrTranslationExchangeInvalidPayload    = core.ErrTranslationExchangeInvalidPayload
	ErrTranslationExchangeLinkageNotFound   = core.ErrTranslationExchangeLinkageNotFound
	ErrTranslationExchangeMissingLinkage    = core.ErrTranslationExchangeMissingLinkage
	ErrTranslationExchangeStaleSourceHash   = core.ErrTranslationExchangeStaleSourceHash
	ErrTranslationExchangeUnsupportedFormat = core.ErrTranslationExchangeUnsupportedFormat
	ErrWorkflowBindingConflict              = core.ErrWorkflowBindingConflict
	ErrWorkflowBindingVersionConflict       = core.ErrWorkflowBindingVersionConflict
	ErrWorkflowInvalidTransition            = core.ErrWorkflowInvalidTransition
	ErrWorkflowNotFound                     = core.ErrWorkflowNotFound
	ErrWorkflowRollbackVersionNotFound      = core.ErrWorkflowRollbackVersionNotFound
	ErrWorkflowVersionConflict              = core.ErrWorkflowVersionConflict
)

type (
	Action                                    = core.Action
	ActionScope                               = core.ActionScope
	ActivityEntry                             = core.ActivityEntry
	ActivityFeed                              = core.ActivityFeed
	ActivityFeedQuerier                       = core.ActivityFeedQuerier
	ActivityFilter                            = core.ActivityFilter
	ActivityLogger                            = core.ActivityLogger
	ActivityModule                            = core.ActivityModule
	ActivityRecord                            = core.ActivityRecord
	ActivityRecordLister                      = core.ActivityRecordLister
	ActivitySink                              = core.ActivitySink
	ActivitySinkAdapter                       = core.ActivitySinkAdapter
	Admin                                     = core.Admin
	AdminActivityEnricherConfig               = core.AdminActivityEnricherConfig
	AdminActorResolver                        = core.AdminActorResolver
	AdminContext                              = core.AdminContext
	AdminObjectResolverConfig                 = core.AdminObjectResolverConfig
	AdminPageGetOptions                       = core.AdminPageGetOptions
	AdminPageListOptions                      = core.AdminPageListOptions
	AdminPageReadService                      = core.AdminPageReadService
	AdminPageRecord                           = core.AdminPageRecord
	AdminPageWriteService                     = core.AdminPageWriteService
	AdminRouter                               = core.AdminRouter
	AssignmentStatus                          = core.AssignmentStatus
	AssignmentType                            = core.AssignmentType
	AuthConfig                                = core.AuthConfig
	Authenticator                             = core.Authenticator
	Authorizer                                = core.Authorizer
	AutosaveConflictError                     = core.AutosaveConflictError
	BulkCommand                               = core.BulkCommand
	BulkConfig                                = core.BulkConfig
	BulkJob                                   = core.BulkJob
	BulkRequest                               = core.BulkRequest
	BulkRoleChangeRequest                     = core.BulkRoleChangeRequest
	BulkRoleChangeResponse                    = core.BulkRoleChangeResponse
	BulkRoleChangeResult                      = core.BulkRoleChangeResult
	BulkRoleChangeSummary                     = core.BulkRoleChangeSummary
	BulkRollbacker                            = core.BulkRollbacker
	BulkService                               = core.BulkService
	BulkStartMsg                              = core.BulkStartMsg
	BunRecordMapper[T any]                    = core.BunRecordMapper[T]
	BunRepositoryAdapter[T any]               = core.BunRepositoryAdapter[T]
	BunRepositoryOption[T any]                = core.BunRepositoryOption[T]
	BunSettingsAdapter                        = core.BunSettingsAdapter
	BunWorkflowBindingRepository              = core.BunWorkflowBindingRepository
	BunWorkflowDefinitionRepository           = core.BunWorkflowDefinitionRepository
	CLIConfig                                 = core.CLIConfig
	CLIGroup                                  = core.CLIGroup
	CMSBlock                                  = core.CMSBlock
	CMSBlockConflictRepository                = core.CMSBlockConflictRepository
	CMSBlockDefinition                        = core.CMSBlockDefinition
	CMSBlockDefinitionRepository              = core.CMSBlockDefinitionRepository
	CMSBlockDefinitionVersion                 = core.CMSBlockDefinitionVersion
	CMSBlockRepository                        = core.CMSBlockRepository
	CMSContainer                              = core.CMSContainer
	CMSContainerBuilder                       = core.CMSContainerBuilder
	CMSContent                                = core.CMSContent
	CMSContentListOption                      = core.CMSContentListOption
	CMSContentRepository                      = core.CMSContentRepository
	CMSContentService                         = core.CMSContentService
	CMSContentTranslationCreator              = core.CMSContentTranslationCreator
	CMSContentType                            = core.CMSContentType
	CMSContentTypeEntryRepository             = core.CMSContentTypeEntryRepository
	CMSContentTypeRepository                  = core.CMSContentTypeRepository
	CMSContentTypeService                     = core.CMSContentTypeService
	CMSLegacyBlockService                     = core.CMSLegacyBlockService
	CMSMenuRepository                         = core.CMSMenuRepository
	CMSMenuService                            = core.CMSMenuService
	CMSOptions                                = core.CMSOptions
	CMSPage                                   = core.CMSPage
	CMSPageRepository                         = core.CMSPageRepository
	CMSWidgetService                          = core.CMSWidgetService
	CRUDRepositoryAdapter                     = core.CRUDRepositoryAdapter
	CommandBus                                = core.CommandBus
	Config                                    = core.Config
	ContentTranslation                        = core.ContentTranslation
	ContentTypeBuilderModule                  = core.ContentTypeBuilderModule
	ContentTypeBuilderOption                  = core.ContentTypeBuilderOption
	ContentTypeCreateMsg                      = core.ContentTypeCreateMsg
	ContentTypeDeleteMsg                      = core.ContentTypeDeleteMsg
	ContentTypePublishMsg                     = core.ContentTypePublishMsg
	ContentTypeUpdateMsg                      = core.ContentTypeUpdateMsg
	ConvertedFields                           = core.ConvertedFields
	CustomLogEntry                            = core.CustomLogEntry
	Dashboard                                 = core.Dashboard
	DashboardDiagnosticsMsg                   = core.DashboardDiagnosticsMsg
	DashboardDiagnosticsReport                = core.DashboardDiagnosticsReport
	DashboardHandle                           = core.DashboardHandle
	DashboardLayout                           = core.DashboardLayout
	DashboardLayoutOverrides                  = core.DashboardLayoutOverrides
	DashboardLayoutRow                        = core.DashboardLayoutRow
	DashboardLayoutSlot                       = core.DashboardLayoutSlot
	DashboardPreferences                      = core.DashboardPreferences
	DashboardPreferencesWithContext           = core.DashboardPreferencesWithContext
	DashboardProviderMsg                      = core.DashboardProviderMsg
	DashboardProviderSpec                     = core.DashboardProviderSpec
	DashboardRenderer                         = core.DashboardRenderer
	DashboardWidgetInstance                   = core.DashboardWidgetInstance
	DebugCollector                            = core.DebugCollector
	DebugConfig                               = core.DebugConfig
	DebugEvent                                = core.DebugEvent
	DebugLayoutMode                           = core.DebugLayoutMode
	DebugLogHandler                           = core.DebugLogHandler
	DebugModule                               = core.DebugModule
	DebugPanel                                = core.DebugPanel
	DebugQueryHook                            = core.DebugQueryHook
	DebugREPLCommand                          = core.DebugREPLCommand
	DebugREPLCommandCatalog                   = core.DebugREPLCommandCatalog
	DebugREPLConfig                           = core.DebugREPLConfig
	DebugREPLOverrideStrategy                 = core.DebugREPLOverrideStrategy
	DebugREPLRequest                          = core.DebugREPLRequest
	DebugREPLSession                          = core.DebugREPLSession
	DebugREPLSessionManager                   = core.DebugREPLSessionManager
	DebugREPLSessionStore                     = core.DebugREPLSessionStore
	DebugSessionSnapshotOptions               = core.DebugSessionSnapshotOptions
	DebugUserSession                          = core.DebugUserSession
	DebugUserSessionStore                     = core.DebugUserSessionStore
	DebugViewContextBuilder                   = core.DebugViewContextBuilder
	DefaultIconRenderer                       = core.DefaultIconRenderer
	DefaultPageMapper                         = core.DefaultPageMapper
	DefaultTranslationQueueAutoCreateHook     = core.DefaultTranslationQueueAutoCreateHook
	DefaultTranslationQueueService            = core.DefaultTranslationQueueService
	DeliveryContentService                    = core.DeliveryContentService
	DeliveryMenuService                       = core.DeliveryMenuService
	DeliveryOptions                           = core.DeliveryOptions
	DeliveryPageService                       = core.DeliveryPageService
	DeliveryServices                          = core.DeliveryServices
	DenyAllStrategy                           = core.DenyAllStrategy
	Dependencies                              = core.Dependencies
	DevErrorContext                           = core.DevErrorContext
	DisabledBulkService                       = core.DisabledBulkService
	DisabledMediaLibrary                      = core.DisabledMediaLibrary
	DisabledNotificationService               = core.DisabledNotificationService
	DispatchFactory                           = core.DispatchFactory
	DoctorCheck                               = core.DoctorCheck
	DoctorCheckOutput                         = core.DoctorCheckOutput
	DoctorCheckResult                         = core.DoctorCheckResult
	DoctorDebugPanel                          = core.DoctorDebugPanel
	DoctorFinding                             = core.DoctorFinding
	DoctorReport                              = core.DoctorReport
	DoctorSeverity                            = core.DoctorSeverity
	DoctorSummary                             = core.DoctorSummary
	DomainErrorCode                           = core.DomainErrorCode
	DynamicPanelFactory                       = core.DynamicPanelFactory
	DynamicPanelFactoryOption                 = core.DynamicPanelFactoryOption
	DynamicPanelHooks                         = core.DynamicPanelHooks
	EnsureMenuParentsOptions                  = core.EnsureMenuParentsOptions
	EnvironmentInfo                           = core.EnvironmentInfo
	ErrorConfig                               = core.ErrorConfig
	ErrorPresenter                            = core.ErrorPresenter
	ExportColumn                              = core.ExportColumn
	ExportConfig                              = core.ExportConfig
	ExportDefinition                          = core.ExportDefinition
	ExportHTTPRegistrar                       = core.ExportHTTPRegistrar
	ExportMetadata                            = core.ExportMetadata
	ExportMetadataProvider                    = core.ExportMetadataProvider
	ExportRegistry                            = core.ExportRegistry
	ExportRouteOptions                        = core.ExportRouteOptions
	ExportRouteWrapper                        = core.ExportRouteWrapper
	FeatureDependencyError                    = core.FeatureDependencyError
	FeatureDisabledError                      = core.FeatureDisabledError
	FeatureFlagsModule                        = core.FeatureFlagsModule
	FeatureKey                                = core.FeatureKey
	Field                                     = core.Field
	FieldTypeCategory                         = core.FieldTypeCategory
	FieldTypeCategoryGroup                    = core.FieldTypeCategoryGroup
	FieldTypeDefinition                       = core.FieldTypeDefinition
	FieldTypeRegistry                         = core.FieldTypeRegistry
	FieldsLogger                              = core.FieldsLogger
	Filter                                    = core.Filter
	FormgenSchemaValidator                    = core.FormgenSchemaValidator
	GoAuthAuthenticator                       = core.GoAuthAuthenticator
	GoAuthAuthenticatorOption                 = core.GoAuthAuthenticatorOption
	GoAuthAuthorizer                          = core.GoAuthAuthorizer
	GoAuthAuthorizerConfig                    = core.GoAuthAuthorizerConfig
	GoCMSContainerAdapter                     = core.GoCMSContainerAdapter
	GoCMSContentAdapter                       = core.GoCMSContentAdapter
	GoCMSContentTypeAdapter                   = core.GoCMSContentTypeAdapter
	GoCMSMenuAdapter                          = core.GoCMSMenuAdapter
	GoCMSTranslationPolicy                    = core.GoCMSTranslationPolicy
	GoCMSWidgetAdapter                        = core.GoCMSWidgetAdapter
	GoOptionsSettingsAdapter                  = core.GoOptionsSettingsAdapter
	GoUsersProfileStore                       = core.GoUsersProfileStore
	GoUsersRoleRepository                     = core.GoUsersRoleRepository
	GoUsersUserRepository                     = core.GoUsersUserRepository
	GuardrailedSchemaValidator                = core.GuardrailedSchemaValidator
	HandlerAuthenticator                      = core.HandlerAuthenticator
	IconCategory                              = core.IconCategory
	IconContributor                           = core.IconContributor
	IconContributorAdapter                    = core.IconContributorAdapter
	IconContributorCallbacks                  = core.IconContributorCallbacks
	IconDefinition                            = core.IconDefinition
	IconLibrary                               = core.IconLibrary
	IconReference                             = core.IconReference
	IconRenderMode                            = core.IconRenderMode
	IconRenderOptions                         = core.IconRenderOptions
	IconRenderer                              = core.IconRenderer
	IconSecurityPolicy                        = core.IconSecurityPolicy
	IconSecurityResult                        = core.IconSecurityResult
	IconSecurityValidator                     = core.IconSecurityValidator
	IconService                               = core.IconService
	IconServiceDefaults                       = core.IconServiceDefaults
	IconServiceOption                         = core.IconServiceOption
	IconType                                  = core.IconType
	InMemoryBulkService                       = core.InMemoryBulkService
	InMemoryContentService                    = core.InMemoryContentService
	InMemoryDashboardPreferences              = core.InMemoryDashboardPreferences
	InMemoryDebugREPLSessionStore             = core.InMemoryDebugREPLSessionStore
	InMemoryDebugUserSessionStore             = core.InMemoryDebugUserSessionStore
	InMemoryMediaLibrary                      = core.InMemoryMediaLibrary
	InMemoryMenuService                       = core.InMemoryMenuService
	InMemoryNotificationService               = core.InMemoryNotificationService
	InMemoryOrganizationStore                 = core.InMemoryOrganizationStore
	InMemoryPreferencesStore                  = core.InMemoryPreferencesStore
	InMemoryProfileStore                      = core.InMemoryProfileStore
	InMemoryTenantStore                       = core.InMemoryTenantStore
	InMemoryTranslationAssignmentRepository   = core.InMemoryTranslationAssignmentRepository
	InMemoryUserStore                         = core.InMemoryUserStore
	InMemoryWidgetService                     = core.InMemoryWidgetService
	InMemoryWorkflowBindingRepository         = core.InMemoryWorkflowBindingRepository
	InMemoryWorkflowDefinitionRepository      = core.InMemoryWorkflowDefinitionRepository
	InvalidDependenciesError                  = core.InvalidDependenciesError
	InvalidFeatureConfigError                 = core.InvalidFeatureConfigError
	JSErrorEntry                              = core.JSErrorEntry
	Job                                       = core.Job
	JobRegistry                               = core.JobRegistry
	ListOptions                               = core.ListOptions
	ListPredicate                             = core.ListPredicate
	LogEntry                                  = core.LogEntry
	Logger                                    = core.Logger
	LoggerProvider                            = core.LoggerProvider
	ManagementContentService                  = core.ManagementContentService
	ManagementContentTypeService              = core.ManagementContentTypeService
	ManagementPageService                     = core.ManagementPageService
	ManagementServices                        = core.ManagementServices
	MediaConfig                               = core.MediaConfig
	MediaItem                                 = core.MediaItem
	MediaLibrary                              = core.MediaLibrary
	MemoryRepository                          = core.MemoryRepository
	Menu                                      = core.Menu
	MenuContributor                           = core.MenuContributor
	MenuHandle                                = core.MenuHandle
	MenuItem                                  = core.MenuItem
	MessageFactory                            = core.MessageFactory
	MissingTranslationsError                  = core.MissingTranslationsError
	Module                                    = core.Module
	ModuleContext                             = core.ModuleContext
	ModuleManifest                            = core.ModuleManifest
	ModuleStartupPolicy                       = core.ModuleStartupPolicy
	ModuleStartupValidator                    = core.ModuleStartupValidator
	Navigation                                = core.Navigation
	NavigationItem                            = core.NavigationItem
	NoopCLIHandler                            = core.NoopCLIHandler
	NoopCMSContainer                          = core.NoopCMSContainer
	NoopTranslator                            = core.NoopTranslator
	Notification                              = core.Notification
	NotificationMarkCommand                   = core.NotificationMarkCommand
	NotificationMarkMsg                       = core.NotificationMarkMsg
	NotificationService                       = core.NotificationService
	ObjectResolverFunc                        = core.ObjectResolverFunc
	ObjectResolverMap                         = core.ObjectResolverMap
	Option                                    = core.Option
	OrganizationMember                        = core.OrganizationMember
	OrganizationPanelRepository               = core.OrganizationPanelRepository
	OrganizationRecord                        = core.OrganizationRecord
	OrganizationRepository                    = core.OrganizationRepository
	OrganizationService                       = core.OrganizationService
	OrganizationsModule                       = core.OrganizationsModule
	PageApplicationService                    = core.PageApplicationService
	PageGetOptions                            = core.PageGetOptions
	PageIncludeDefaults                       = core.PageIncludeDefaults
	PageListOptions                           = core.PageListOptions
	PageMapper                                = core.PageMapper
	PageReadDefaults                          = core.PageReadDefaults
	PageReadOptions                           = core.PageReadOptions
	PageTranslation                           = core.PageTranslation
	Panel                                     = core.Panel
	PanelBuilder                              = core.PanelBuilder
	PanelEntryMode                            = core.PanelEntryMode
	PanelFormAdapter                          = core.PanelFormAdapter
	PanelFormRequest                          = core.PanelFormRequest
	PanelHooks                                = core.PanelHooks
	PanelPermissions                          = core.PanelPermissions
	PanelSubresource                          = core.PanelSubresource
	PanelSubresourceRepository                = core.PanelSubresourceRepository
	PanelSubresourceResponder                 = core.PanelSubresourceResponder
	PanelTab                                  = core.PanelTab
	PanelTabCollisionHandler                  = core.PanelTabCollisionHandler
	PanelTabPermissionEvaluator               = core.PanelTabPermissionEvaluator
	PanelTabScope                             = core.PanelTabScope
	PanelTabTarget                            = core.PanelTabTarget
	PanelUIRouteMode                          = core.PanelUIRouteMode
	PermissionDeniedError                     = core.PermissionDeniedError
	PermissionEntry                           = core.PermissionEntry
	PermissionsDebugPanel                     = core.PermissionsDebugPanel
	PermissionsDebugSnapshot                  = core.PermissionsDebugSnapshot
	PersistedWorkflow                         = core.PersistedWorkflow
	PersistedWorkflowListOptions              = core.PersistedWorkflowListOptions
	PersistedWorkflowStatus                   = core.PersistedWorkflowStatus
	PreferenceLevel                           = core.PreferenceLevel
	PreferenceScope                           = core.PreferenceScope
	PreferenceSnapshot                        = core.PreferenceSnapshot
	PreferenceTrace                           = core.PreferenceTrace
	PreferenceTraceLayer                      = core.PreferenceTraceLayer
	PreferencesDeleteInput                    = core.PreferencesDeleteInput
	PreferencesModule                         = core.PreferencesModule
	PreferencesOption                         = core.PreferencesOption
	PreferencesRepository                     = core.PreferencesRepository
	PreferencesResolveInput                   = core.PreferencesResolveInput
	PreferencesService                        = core.PreferencesService
	PreferencesStore                          = core.PreferencesStore
	PreferencesStoreAdapter                   = core.PreferencesStoreAdapter
	PreferencesUpsertInput                    = core.PreferencesUpsertInput
	PreferencesViewContextBuilder             = core.PreferencesViewContextBuilder
	PreviewService                            = core.PreviewService
	PreviewToken                              = core.PreviewToken
	Priority                                  = core.Priority
	ProfileModule                             = core.ProfileModule
	ProfileRepository                         = core.ProfileRepository
	ProfileService                            = core.ProfileService
	ProfileStore                              = core.ProfileStore
	RateLimiter                               = core.RateLimiter
	Registry                                  = core.Registry
	Repository                                = core.Repository
	RepositoryTranslationCreator              = core.RepositoryTranslationCreator
	RequestEntry                              = core.RequestEntry
	RequestInfo                               = core.RequestInfo
	RequiredFieldsValidationStrategy          = core.RequiredFieldsValidationStrategy
	ResolvedSetting                           = core.ResolvedSetting
	ResolvedWidget                            = core.ResolvedWidget
	RingBuffer[T any]                         = core.RingBuffer[T]
	RoleAssignmentLookup                      = core.RoleAssignmentLookup
	RolePanelRepository                       = core.RolePanelRepository
	RoleRecord                                = core.RoleRecord
	RoleRepository                            = core.RoleRepository
	RoleRepositoryLookup                      = core.RoleRepositoryLookup
	RoleWorkflowAuthorizer                    = core.RoleWorkflowAuthorizer
	RoleWorkflowAuthorizerOption              = core.RoleWorkflowAuthorizerOption
	RouteEntry                                = core.RouteEntry
	RouterContext                             = core.RouterContext
	SQLEntry                                  = core.SQLEntry
	Schema                                    = core.Schema
	SchemaGuardrails                          = core.SchemaGuardrails
	SchemaGuardrailsOption                    = core.SchemaGuardrailsOption
	SchemaPreviewFallback                     = core.SchemaPreviewFallback
	SchemaPreviewer                           = core.SchemaPreviewer
	SchemaRegistryEntry                       = core.SchemaRegistryEntry
	SchemaRegistryPayload                     = core.SchemaRegistryPayload
	SchemaToFieldsConverter                   = core.SchemaToFieldsConverter
	SchemaValidationOptions                   = core.SchemaValidationOptions
	SchemaValidationResult                    = core.SchemaValidationResult
	SchemaValidator                           = core.SchemaValidator
	SearchAdapter                             = core.SearchAdapter
	SearchEngine                              = core.SearchEngine
	SearchResult                              = core.SearchResult
	SettingDefinition                         = core.SettingDefinition
	SettingFieldEnricher                      = core.SettingFieldEnricher
	SettingOption                             = core.SettingOption
	SettingOptionsProvider                    = core.SettingOptionsProvider
	SettingRecord                             = core.SettingRecord
	SettingValidator                          = core.SettingValidator
	SettingsAdapter                           = core.SettingsAdapter
	SettingsBundle                            = core.SettingsBundle
	SettingsForm                              = core.SettingsForm
	SettingsFormAdapter                       = core.SettingsFormAdapter
	SettingsScope                             = core.SettingsScope
	SettingsService                           = core.SettingsService
	SettingsUpdateCommand                     = core.SettingsUpdateCommand
	SettingsUpdateMsg                         = core.SettingsUpdateMsg
	SettingsValidationErrors                  = core.SettingsValidationErrors
	SignedTokenStrategy                       = core.SignedTokenStrategy
	SimpleWorkflowEngine                      = core.SimpleWorkflowEngine
	SourceContext                             = core.SourceContext
	SourceLine                                = core.SourceLine
	StackFrameInfo                            = core.StackFrameInfo
	StaticKeyStrategy                         = core.StaticKeyStrategy
	TenantMember                              = core.TenantMember
	TenantPanelRepository                     = core.TenantPanelRepository
	TenantRecord                              = core.TenantRecord
	TenantRepository                          = core.TenantRepository
	TenantService                             = core.TenantService
	TenantsModule                             = core.TenantsModule
	ThemeProvider                             = core.ThemeProvider
	ThemeSelection                            = core.ThemeSelection
	ThemeSelector                             = core.ThemeSelector
	TransitionInput                           = core.TransitionInput
	TransitionResult                          = core.TransitionResult
	TranslationAlreadyExistsError             = core.TranslationAlreadyExistsError
	TranslationAssignment                     = core.TranslationAssignment
	TranslationAssignmentConflictError        = core.TranslationAssignmentConflictError
	TranslationAssignmentPanelRepository      = core.TranslationAssignmentPanelRepository
	TranslationAssignmentRepository           = core.TranslationAssignmentRepository
	TranslationAssignmentVersionConflictError = core.TranslationAssignmentVersionConflictError
	TranslationBundle[T any]                  = core.TranslationBundle[T]
	TranslationCheckOptions                   = core.TranslationCheckOptions
	TranslationCreateInput                    = core.TranslationCreateInput
	TranslationExchangeApplier                = core.TranslationExchangeApplier
	TranslationExchangeApplyRequest           = core.TranslationExchangeApplyRequest
	TranslationExchangeConflictError          = core.TranslationExchangeConflictError
	TranslationExchangeConflictInfo           = core.TranslationExchangeConflictInfo
	TranslationExchangeExporter               = core.TranslationExchangeExporter
	TranslationExchangeInvalidPayloadError    = core.TranslationExchangeInvalidPayloadError
	TranslationExchangeLinkage                = core.TranslationExchangeLinkage
	TranslationExchangeLinkageKey             = core.TranslationExchangeLinkageKey
	TranslationExchangeResult                 = core.TranslationExchangeResult
	TranslationExchangeRow                    = core.TranslationExchangeRow
	TranslationExchangeRowResult              = core.TranslationExchangeRowResult
	TranslationExchangeService                = core.TranslationExchangeService
	TranslationExchangeStore                  = core.TranslationExchangeStore
	TranslationExchangeSummary                = core.TranslationExchangeSummary
	TranslationExchangeUnsupportedFormatError = core.TranslationExchangeUnsupportedFormatError
	TranslationExchangeValidator              = core.TranslationExchangeValidator
	TranslationExportCommand                  = core.TranslationExportCommand
	TranslationExportFilter                   = core.TranslationExportFilter
	TranslationExportInput                    = core.TranslationExportInput
	TranslationExportResult                   = core.TranslationExportResult
	TranslationImportApplyCommand             = core.TranslationImportApplyCommand
	TranslationImportApplyInput               = core.TranslationImportApplyInput
	TranslationImportRunCommand               = core.TranslationImportRunCommand
	TranslationImportRunInput                 = core.TranslationImportRunInput
	TranslationImportRunResult                = core.TranslationImportRunResult
	TranslationImportRunTriggerBuilder        = core.TranslationImportRunTriggerBuilder
	TranslationImportRunTriggerCommand        = core.TranslationImportRunTriggerCommand
	TranslationImportRunTriggerInput          = core.TranslationImportRunTriggerInput
	TranslationImportValidateCommand          = core.TranslationImportValidateCommand
	TranslationImportValidateInput            = core.TranslationImportValidateInput
	TranslationMeta                           = core.TranslationMeta
	TranslationMetrics                        = core.TranslationMetrics
	TranslationPolicy                         = core.TranslationPolicy
	TranslationPolicyFunc                     = core.TranslationPolicyFunc
	TranslationPolicyInput                    = core.TranslationPolicyInput
	TranslationQueueApproveCommand            = core.TranslationQueueApproveCommand
	TranslationQueueApproveInput              = core.TranslationQueueApproveInput
	TranslationQueueArchiveCommand            = core.TranslationQueueArchiveCommand
	TranslationQueueArchiveInput              = core.TranslationQueueArchiveInput
	TranslationQueueAssignCommand             = core.TranslationQueueAssignCommand
	TranslationQueueAssignInput               = core.TranslationQueueAssignInput
	TranslationQueueAutoCreateHook            = core.TranslationQueueAutoCreateHook
	TranslationQueueAutoCreateInput           = core.TranslationQueueAutoCreateInput
	TranslationQueueAutoCreateResult          = core.TranslationQueueAutoCreateResult
	TranslationQueueBulkArchiveCommand        = core.TranslationQueueBulkArchiveCommand
	TranslationQueueBulkArchiveInput          = core.TranslationQueueBulkArchiveInput
	TranslationQueueBulkAssignCommand         = core.TranslationQueueBulkAssignCommand
	TranslationQueueBulkAssignInput           = core.TranslationQueueBulkAssignInput
	TranslationQueueBulkPriorityCommand       = core.TranslationQueueBulkPriorityCommand
	TranslationQueueBulkPriorityInput         = core.TranslationQueueBulkPriorityInput
	TranslationQueueBulkReleaseCommand        = core.TranslationQueueBulkReleaseCommand
	TranslationQueueBulkReleaseInput          = core.TranslationQueueBulkReleaseInput
	TranslationQueueClaimCommand              = core.TranslationQueueClaimCommand
	TranslationQueueClaimInput                = core.TranslationQueueClaimInput
	TranslationQueueRejectCommand             = core.TranslationQueueRejectCommand
	TranslationQueueRejectInput               = core.TranslationQueueRejectInput
	TranslationQueueReleaseCommand            = core.TranslationQueueReleaseCommand
	TranslationQueueReleaseInput              = core.TranslationQueueReleaseInput
	TranslationQueueService                   = core.TranslationQueueService
	TranslationQueueStatsFromRepository       = core.TranslationQueueStatsFromRepository
	TranslationQueueStatsService              = core.TranslationQueueStatsService
	TranslationQueueStatsSnapshot             = core.TranslationQueueStatsSnapshot
	TranslationQueueSubmitCommand             = core.TranslationQueueSubmitCommand
	TranslationQueueSubmitInput               = core.TranslationQueueSubmitInput
	TranslationRequirements                   = core.TranslationRequirements
	TranslationRequirementsResolver           = core.TranslationRequirementsResolver
	TranslationRequirementsResolverFunc       = core.TranslationRequirementsResolverFunc
	Translator                                = core.Translator
	TranslatorAware                           = core.TranslatorAware
	URLConfig                                 = core.URLConfig
	URLNamespaceConfig                        = core.URLNamespaceConfig
	UUIDRoleAssignmentLookup                  = core.UUIDRoleAssignmentLookup
	UserActivateMsg                           = core.UserActivateMsg
	UserArchiveMsg                            = core.UserArchiveMsg
	UserBulkAssignRoleMsg                     = core.UserBulkAssignRoleMsg
	UserBulkUnassignRoleMsg                   = core.UserBulkUnassignRoleMsg
	UserDisableMsg                            = core.UserDisableMsg
	UserManagementModule                      = core.UserManagementModule
	UserManagementModuleOption                = core.UserManagementModuleOption
	UserManagementService                     = core.UserManagementService
	UserPanelRepository                       = core.UserPanelRepository
	UserPreferences                           = core.UserPreferences
	UserProfile                               = core.UserProfile
	UserProfilesPanelRepository               = core.UserProfilesPanelRepository
	UserRecord                                = core.UserRecord
	UserRepository                            = core.UserRepository
	UserSuspendMsg                            = core.UserSuspendMsg
	WidgetArea                                = core.WidgetArea
	WidgetAreaDefinition                      = core.WidgetAreaDefinition
	WidgetDefinition                          = core.WidgetDefinition
	WidgetDefinitionRepository                = core.WidgetDefinitionRepository
	WidgetInstance                            = core.WidgetInstance
	WidgetInstanceFilter                      = core.WidgetInstanceFilter
	WidgetInstanceRepository                  = core.WidgetInstanceRepository
	WidgetLayout                              = core.WidgetLayout
	WidgetMetadata                            = core.WidgetMetadata
	WidgetProvider                            = core.WidgetProvider
	WorkflowAuthorizer                        = core.WorkflowAuthorizer
	WorkflowBinding                           = core.WorkflowBinding
	WorkflowBindingConflictError              = core.WorkflowBindingConflictError
	WorkflowBindingListOptions                = core.WorkflowBindingListOptions
	WorkflowBindingRepository                 = core.WorkflowBindingRepository
	WorkflowBindingResolution                 = core.WorkflowBindingResolution
	WorkflowBindingResolveInput               = core.WorkflowBindingResolveInput
	WorkflowBindingScopeType                  = core.WorkflowBindingScopeType
	WorkflowBindingStatus                     = core.WorkflowBindingStatus
	WorkflowBindingVersionConflictError       = core.WorkflowBindingVersionConflictError
	WorkflowDefinition                        = core.WorkflowDefinition
	WorkflowDefinitionChecker                 = core.WorkflowDefinitionChecker
	WorkflowDefinitionRepository              = core.WorkflowDefinitionRepository
	WorkflowEngine                            = core.WorkflowEngine
	WorkflowRegistrar                         = core.WorkflowRegistrar
	WorkflowRuntime                           = core.WorkflowRuntime
	WorkflowRuntimeService                    = core.WorkflowRuntimeService
	WorkflowTransition                        = core.WorkflowTransition
	WorkflowValidationErrors                  = core.WorkflowValidationErrors
	WorkflowVersionConflictError              = core.WorkflowVersionConflictError
)

func ActionDisabledReasonCodes() []string {
	return core.ActionDisabledReasonCodes()
}

func AttachErrorContext(err error, mapped *errors.Error) *errors.Error {
	return core.AttachErrorContext(err, mapped)
}

func BlockEditorDescriptor(basePath string) components.Descriptor {
	return core.BlockEditorDescriptor(basePath)
}

func BlockFieldTypeGroups() []FieldTypeCategoryGroup {
	return core.BlockFieldTypeGroups()
}

func BlockLibraryPickerDescriptor(basePath string) components.Descriptor {
	return core.BlockLibraryPickerDescriptor(basePath)
}

func BlockLibraryPickerDescriptorWithAPIBase(basePath string, apiBase string) components.Descriptor {
	return core.BlockLibraryPickerDescriptorWithAPIBase(basePath, apiBase)
}

func BoolPtr(value bool) *bool {
	return core.BoolPtr(value)
}

func BuildGoCMSContainer(ctx context.Context, cfg Config) (CMSContainer, error) {
	return core.BuildGoCMSContainer(ctx, cfg)
}

func BuiltinEmojiLibrary() IconLibrary {
	return core.BuiltinEmojiLibrary()
}

func BuiltinIconoirLibrary() IconLibrary {
	return core.BuiltinIconoirLibrary()
}

func BuiltinLucideLibrary() IconLibrary {
	return core.BuiltinLucideLibrary()
}

func CanonicalPolicyEntityKey(value string) string {
	return core.CanonicalPolicyEntityKey(value)
}

func CaptureJSErrorContext(collector *DebugCollector, c router.Context, viewCtx router.ViewContext) router.ViewContext {
	return core.CaptureJSErrorContext(collector, c, viewCtx)
}

func CaptureViewContext(collector *DebugCollector, viewCtx router.ViewContext) router.ViewContext {
	return core.CaptureViewContext(collector, viewCtx)
}

func CaptureViewContextForRequest(collector *DebugCollector, c router.Context, viewCtx router.ViewContext) router.ViewContext {
	return core.CaptureViewContextForRequest(collector, c, viewCtx)
}

func CollectIconContributions(contributor IconContributor, callbacks IconContributorCallbacks) error {
	return core.CollectIconContributions(contributor, callbacks)
}

func DebugRequestMiddleware(collector *DebugCollector) router.MiddlewareFunc {
	return core.DebugRequestMiddleware(collector)
}

func DefaultBlockFieldTypeRegistry() *FieldTypeRegistry {
	return core.DefaultBlockFieldTypeRegistry()
}

func DefaultCMSWorkflowActions() []Action {
	return core.DefaultCMSWorkflowActions()
}

func DefaultDebugPanels() []string {
	return core.DefaultDebugPanels()
}

func DefaultDebugToolbarPanels() []string {
	return core.DefaultDebugToolbarPanels()
}

func DefaultErrorPresenter() ErrorPresenter {
	return core.DefaultErrorPresenter()
}

func DefaultIconSecurityPolicy() IconSecurityPolicy {
	return core.DefaultIconSecurityPolicy()
}

func DefaultSchemaRateLimiter() *RateLimiter {
	return core.DefaultSchemaRateLimiter()
}

func DeliveryGraphQLControllers() []registrar.Controller {
	return core.DeliveryGraphQLControllers()
}

func DomainErrorCodeFor(code string) (DomainErrorCode, bool) {
	return core.DomainErrorCodeFor(code)
}

func DomainErrorCodes() []DomainErrorCode {
	return core.DomainErrorCodes()
}

func EnrichLayoutViewContext(adm *Admin, c router.Context, view router.ViewContext, active string) router.ViewContext {
	return core.EnrichLayoutViewContext(adm, c, view, active)
}

func EnrichStackFrames(frames []StackFrameInfo, contextLines int, maxFrames int) []StackFrameInfo {
	return core.EnrichStackFrames(frames, contextLines, maxFrames)
}

func EnsureMenuParents(ctx context.Context, opts EnsureMenuParentsOptions) error {
	return core.EnsureMenuParents(ctx, opts)
}

func EnsureMenuUUID(raw string) string {
	return core.EnsureMenuUUID(raw)
}

func EnvironmentFromContext(ctx context.Context) string {
	return core.EnvironmentFromContext(ctx)
}

func ExtractSourceContext(filePath string, errorLine int, contextLines int) *SourceContext {
	return core.ExtractSourceContext(filePath, errorLine, contextLines)
}

func GetSVGFieldTypeMapping() map[string]string {
	return core.GetSVGFieldTypeMapping()
}

func GetTranslationAssignmentMigrationsFS() fs.FS {
	return core.GetTranslationAssignmentMigrationsFS()
}

func GetWorkflowRuntimeMigrationsFS() fs.FS {
	return core.GetWorkflowRuntimeMigrationsFS()
}

func IsTranslationMissing(err error) bool {
	return core.IsTranslationMissing(err)
}

func LocaleFromContext(ctx context.Context) string {
	return core.LocaleFromContext(ctx)
}

func ManagementGraphQLControllers() []registrar.Controller {
	return core.ManagementGraphQLControllers()
}

func MenuUUIDFromSlug(slug string) string {
	return core.MenuUUIDFromSlug(slug)
}

func New(cfg Config, deps Dependencies) (*Admin, error) {
	return core.New(cfg, deps)
}

func NewActivityFeed(opts ...func(*ActivityFeed)) *ActivityFeed {
	return core.NewActivityFeed(opts...)
}

func NewActivityModule() *ActivityModule {
	return core.NewActivityModule()
}

func NewActivitySinkAdapter(logger ActivityLogger, lister ActivityRecordLister) *ActivitySinkAdapter {
	return core.NewActivitySinkAdapter(logger, lister)
}

func NewAdminActivityEnricher(cfg AdminActivityEnricherConfig) activity.ActivityEnricher {
	return core.NewAdminActivityEnricher(cfg)
}

func NewAdminObjectResolver(cfg AdminObjectResolverConfig) activity.ObjectResolver {
	return core.NewAdminObjectResolver(cfg)
}

func NewBunRepositoryAdapter[T any](repo repository.Repository[T], opts ...BunRepositoryOption[T]) *BunRepositoryAdapter[T] {
	return core.NewBunRepositoryAdapter[T](repo, opts...)
}

func NewBunSettingsAdapter(db *bun.DB, repoOptions ...repository.Option) (*BunSettingsAdapter, error) {
	return core.NewBunSettingsAdapter(db, repoOptions...)
}

func NewBunWorkflowBindingRepository(db *bun.DB) *BunWorkflowBindingRepository {
	return core.NewBunWorkflowBindingRepository(db)
}

func NewBunWorkflowDefinitionRepository(db *bun.DB) *BunWorkflowDefinitionRepository {
	return core.NewBunWorkflowDefinitionRepository(db)
}

func NewCMSBlockConflictRepository(content CMSContentService) *CMSBlockConflictRepository {
	return core.NewCMSBlockConflictRepository(content)
}

func NewCMSBlockDefinitionRepository(content CMSContentService, types CMSContentTypeService) *CMSBlockDefinitionRepository {
	return core.NewCMSBlockDefinitionRepository(content, types)
}

func NewCMSBlockRepository(content CMSContentService) *CMSBlockRepository {
	return core.NewCMSBlockRepository(content)
}

func NewCMSContentRepository(content CMSContentService) *CMSContentRepository {
	return core.NewCMSContentRepository(content)
}

func NewCMSContentTypeEntryRepository(content CMSContentService, contentType CMSContentType) *CMSContentTypeEntryRepository {
	return core.NewCMSContentTypeEntryRepository(content, contentType)
}

func NewCMSContentTypeRepository(types CMSContentTypeService) *CMSContentTypeRepository {
	return core.NewCMSContentTypeRepository(types)
}

func NewCMSMenuRepository(menu CMSMenuService, defaultCode string) *CMSMenuRepository {
	return core.NewCMSMenuRepository(menu, defaultCode)
}

func NewCMSPageRepository(content CMSContentService) *CMSPageRepository {
	return core.NewCMSPageRepository(content)
}

func NewCRUDContext(ctx context.Context) crud.Context {
	return core.NewCRUDContext(ctx)
}

func NewCRUDRepositoryAdapter(service crud.Service[map[string]any]) *CRUDRepositoryAdapter {
	return core.NewCRUDRepositoryAdapter(service)
}

func NewCommandBus(enabled bool) *CommandBus {
	return core.NewCommandBus(enabled)
}

func NewContentTypeBuilderModule(opts ...ContentTypeBuilderOption) *ContentTypeBuilderModule {
	return core.NewContentTypeBuilderModule(opts...)
}

func NewDashboard() *Dashboard {
	return core.NewDashboard()
}

func NewDashboardPreferencesAdapter(service *PreferencesService) DashboardPreferences {
	return core.NewDashboardPreferencesAdapter(service)
}

func NewDebugCollector(cfg DebugConfig) *DebugCollector {
	return core.NewDebugCollector(cfg)
}

func NewDebugLogHandler(collector *DebugCollector, next slog.Handler) *DebugLogHandler {
	return core.NewDebugLogHandler(collector, next)
}

func NewDebugModule(config DebugConfig) *DebugModule {
	return core.NewDebugModule(config)
}

func NewDebugQueryHook(collector *DebugCollector) *DebugQueryHook {
	return core.NewDebugQueryHook(collector)
}

func NewDebugQueryHookProvider(provider func() *DebugCollector) *DebugQueryHook {
	return core.NewDebugQueryHookProvider(provider)
}

func NewDebugREPLCommandCatalog() *DebugREPLCommandCatalog {
	return core.NewDebugREPLCommandCatalog()
}

func NewDebugREPLSessionManager(store DebugREPLSessionStore, cfg DebugREPLConfig) *DebugREPLSessionManager {
	return core.NewDebugREPLSessionManager(store, cfg)
}

func NewDefaultIconRenderer(policy IconSecurityPolicy) *DefaultIconRenderer {
	return core.NewDefaultIconRenderer(policy)
}

func NewDeliveryContentService(container CMSContainer, opts DeliveryOptions) *DeliveryContentService {
	return core.NewDeliveryContentService(container, opts)
}

func NewDeliveryMenuService(container CMSContainer, opts DeliveryOptions) *DeliveryMenuService {
	return core.NewDeliveryMenuService(container, opts)
}

func NewDeliveryPageService(container CMSContainer, opts DeliveryOptions) *DeliveryPageService {
	return core.NewDeliveryPageService(container, opts)
}

func NewDeliveryServices(container CMSContainer, opts DeliveryOptions) DeliveryServices {
	return core.NewDeliveryServices(container, opts)
}

func NewDoctorDebugPanel(admin *Admin) *DoctorDebugPanel {
	return core.NewDoctorDebugPanel(admin)
}

func NewDomainError(code string, message string, meta map[string]any) *errors.Error {
	return core.NewDomainError(code, message, meta)
}

func NewDynamicPanelFactory(admin *Admin, opts ...DynamicPanelFactoryOption) *DynamicPanelFactory {
	return core.NewDynamicPanelFactory(admin, opts...)
}

func NewErrorPresenter(cfg ErrorConfig, mappers ...errors.ErrorMapper) ErrorPresenter {
	return core.NewErrorPresenter(cfg, mappers...)
}

func NewFeatureFlagsModule() *FeatureFlagsModule {
	return core.NewFeatureFlagsModule()
}

func NewFieldTypeRegistry() *FieldTypeRegistry {
	return core.NewFieldTypeRegistry()
}

func NewFormgenSchemaValidator(basePath string) (*FormgenSchemaValidator, error) {
	return core.NewFormgenSchemaValidator(basePath)
}

func NewFormgenSchemaValidatorWithAPIBase(basePath string, apiBase string) (*FormgenSchemaValidator, error) {
	return core.NewFormgenSchemaValidatorWithAPIBase(basePath, apiBase)
}

func NewGoAuthAuthenticator(routeAuth *auth.RouteAuthenticator, cfg auth.Config, opts ...GoAuthAuthenticatorOption) *GoAuthAuthenticator {
	return core.NewGoAuthAuthenticator(routeAuth, cfg, opts...)
}

func NewGoAuthAuthorizer(cfg GoAuthAuthorizerConfig) *GoAuthAuthorizer {
	return core.NewGoAuthAuthorizer(cfg)
}

func NewGoCMSAdminPageReadAdapter(service cms.AdminPageReadService) AdminPageReadService {
	return core.NewGoCMSAdminPageReadAdapter(service)
}

func NewGoCMSContainerAdapter(container any) *GoCMSContainerAdapter {
	return core.NewGoCMSContainerAdapter(container)
}

func NewGoCMSContentAdapter(contentSvc any, blockSvc any, contentTypeSvc CMSContentTypeService) CMSContentService {
	return core.NewGoCMSContentAdapter(contentSvc, blockSvc, contentTypeSvc)
}

func NewGoCMSContentTypeAdapter(service any) CMSContentTypeService {
	return core.NewGoCMSContentTypeAdapter(service)
}

func NewGoCMSMenuAdapter(service cms.MenuService) *GoCMSMenuAdapter {
	return core.NewGoCMSMenuAdapter(service)
}

func NewGoCMSMenuAdapterFromAny(service any) *GoCMSMenuAdapter {
	return core.NewGoCMSMenuAdapterFromAny(service)
}

func NewGoCMSWidgetAdapter(service any) *GoCMSWidgetAdapter {
	return core.NewGoCMSWidgetAdapter(service)
}

func NewGoOptionsSettingsAdapter() *GoOptionsSettingsAdapter {
	return core.NewGoOptionsSettingsAdapter()
}

func NewGoUsersProfileStore(repo types.ProfileRepository, scopeResolver func(context.Context) types.ScopeFilter) *GoUsersProfileStore {
	return core.NewGoUsersProfileStore(repo, scopeResolver)
}

func NewGoUsersRoleRepository(registry types.RoleRegistry, scopeResolver func(context.Context) types.ScopeFilter) *GoUsersRoleRepository {
	return core.NewGoUsersRoleRepository(registry, scopeResolver)
}

func NewGoUsersUserRepository(auth types.AuthRepository, inventory types.UserInventoryRepository, scopeResolver func(context.Context) types.ScopeFilter) *GoUsersUserRepository {
	return core.NewGoUsersUserRepository(auth, inventory, scopeResolver)
}

func NewGuardrailedSchemaValidator(inner SchemaValidator, guardrails *SchemaGuardrails) *GuardrailedSchemaValidator {
	return core.NewGuardrailedSchemaValidator(inner, guardrails)
}

func NewIconContributorAdapter(libraries []IconLibrary, icons []IconDefinition) *IconContributorAdapter {
	return core.NewIconContributorAdapter(libraries, icons)
}

func NewIconSecurityValidator(policy IconSecurityPolicy) *IconSecurityValidator {
	return core.NewIconSecurityValidator(policy)
}

func NewIconService(opts ...IconServiceOption) *IconService {
	return core.NewIconService(opts...)
}

func NewInMemoryBulkService() *InMemoryBulkService {
	return core.NewInMemoryBulkService()
}

func NewInMemoryContentService() *InMemoryContentService {
	return core.NewInMemoryContentService()
}

func NewInMemoryDashboardPreferences() *InMemoryDashboardPreferences {
	return core.NewInMemoryDashboardPreferences()
}

func NewInMemoryDebugREPLSessionStore() *InMemoryDebugREPLSessionStore {
	return core.NewInMemoryDebugREPLSessionStore()
}

func NewInMemoryDebugUserSessionStore() *InMemoryDebugUserSessionStore {
	return core.NewInMemoryDebugUserSessionStore()
}

func NewInMemoryMediaLibrary(baseURL string) *InMemoryMediaLibrary {
	return core.NewInMemoryMediaLibrary(baseURL)
}

func NewInMemoryMenuService() *InMemoryMenuService {
	return core.NewInMemoryMenuService()
}

func NewInMemoryNotificationService() *InMemoryNotificationService {
	return core.NewInMemoryNotificationService()
}

func NewInMemoryOrganizationStore() *InMemoryOrganizationStore {
	return core.NewInMemoryOrganizationStore()
}

func NewInMemoryPreferencesStore() *InMemoryPreferencesStore {
	return core.NewInMemoryPreferencesStore()
}

func NewInMemoryProfileStore() *InMemoryProfileStore {
	return core.NewInMemoryProfileStore()
}

func NewInMemoryTenantStore() *InMemoryTenantStore {
	return core.NewInMemoryTenantStore()
}

func NewInMemoryTranslationAssignmentRepository() *InMemoryTranslationAssignmentRepository {
	return core.NewInMemoryTranslationAssignmentRepository()
}

func NewInMemoryUserStore() *InMemoryUserStore {
	return core.NewInMemoryUserStore()
}

func NewInMemoryWidgetService() *InMemoryWidgetService {
	return core.NewInMemoryWidgetService()
}

func NewInMemoryWorkflowBindingRepository() *InMemoryWorkflowBindingRepository {
	return core.NewInMemoryWorkflowBindingRepository()
}

func NewInMemoryWorkflowDefinitionRepository() *InMemoryWorkflowDefinitionRepository {
	return core.NewInMemoryWorkflowDefinitionRepository()
}

func NewJobRegistry() *JobRegistry {
	return core.NewJobRegistry()
}

func NewManagementContentService(container CMSContainer, opts DeliveryOptions) *ManagementContentService {
	return core.NewManagementContentService(container, opts)
}

func NewManagementContentTypeService(container CMSContainer) *ManagementContentTypeService {
	return core.NewManagementContentTypeService(container)
}

func NewManagementPageService(container CMSContainer, opts DeliveryOptions) *ManagementPageService {
	return core.NewManagementPageService(container, opts)
}

func NewManagementServices(container CMSContainer, opts DeliveryOptions) ManagementServices {
	return core.NewManagementServices(container, opts)
}

func NewMemoryRepository() *MemoryRepository {
	return core.NewMemoryRepository()
}

func NewNavigation(menuSvc CMSMenuService, authorizer Authorizer) *Navigation {
	return core.NewNavigation(menuSvc, authorizer)
}

func NewNoopCMSContainer() *NoopCMSContainer {
	return core.NewNoopCMSContainer()
}

func NewOrganizationPanelRepository(service *OrganizationService) *OrganizationPanelRepository {
	return core.NewOrganizationPanelRepository(service)
}

func NewOrganizationService(repo OrganizationRepository) *OrganizationService {
	return core.NewOrganizationService(repo)
}

func NewOrganizationsModule() *OrganizationsModule {
	return core.NewOrganizationsModule()
}

func NewPermissionsDebugPanel(admin *Admin) *PermissionsDebugPanel {
	return core.NewPermissionsDebugPanel(admin)
}

func NewPreferencesModule() *PreferencesModule {
	return core.NewPreferencesModule()
}

func NewPreferencesRepository(admin *Admin) *PreferencesRepository {
	return core.NewPreferencesRepository(admin)
}

func NewPreferencesService(store PreferencesStore) *PreferencesService {
	return core.NewPreferencesService(store)
}

func NewPreferencesStoreAdapter(store PreferencesStore, opts ...PreferencesOption) *PreferencesStoreAdapter {
	return core.NewPreferencesStoreAdapter(store, opts...)
}

func NewPreviewService(secret string) *PreviewService {
	return core.NewPreviewService(secret)
}

func NewProfileModule() *ProfileModule {
	return core.NewProfileModule()
}

func NewProfileRepository(service *ProfileService, defaultLocale string) *ProfileRepository {
	return core.NewProfileRepository(service, defaultLocale)
}

func NewProfileService(store ProfileStore) *ProfileService {
	return core.NewProfileService(store)
}

func NewRateLimiter(maxRequests int, window time.Duration) *RateLimiter {
	return core.NewRateLimiter(maxRequests, window)
}

func NewRegistry() *Registry {
	return core.NewRegistry()
}

func NewRingBuffer[T any](capacity int) *RingBuffer[T] {
	return core.NewRingBuffer[T](capacity)
}

func NewRoleFormGenerator(cfg Config) (*orchestrator.Orchestrator, error) {
	return core.NewRoleFormGenerator(cfg)
}

func NewRolePanelRepository(service *UserManagementService) *RolePanelRepository {
	return core.NewRolePanelRepository(service)
}

func NewRoleWorkflowAuthorizer(minRole string, opts ...RoleWorkflowAuthorizerOption) WorkflowAuthorizer {
	return core.NewRoleWorkflowAuthorizer(minRole, opts...)
}

func NewSchemaGuardrails() *SchemaGuardrails {
	return core.NewSchemaGuardrails()
}

func NewSchemaToFieldsConverter() *SchemaToFieldsConverter {
	return core.NewSchemaToFieldsConverter()
}

func NewSearchEngine(authorizer Authorizer) *SearchEngine {
	return core.NewSearchEngine(authorizer)
}

func NewSettingsFormAdapter(service *SettingsService, theme string, tokens map[string]string) *SettingsFormAdapter {
	return core.NewSettingsFormAdapter(service, theme, tokens)
}

func NewSettingsService() *SettingsService {
	return core.NewSettingsService()
}

func NewSimpleWorkflowEngine() *SimpleWorkflowEngine {
	return core.NewSimpleWorkflowEngine()
}

func NewTenantPanelRepository(service *TenantService) *TenantPanelRepository {
	return core.NewTenantPanelRepository(service)
}

func NewTenantService(repo TenantRepository) *TenantService {
	return core.NewTenantService(repo)
}

func NewTenantsModule() *TenantsModule {
	return core.NewTenantsModule()
}

func NewTranslationAssignmentPanelRepository(repo TranslationAssignmentRepository) *TranslationAssignmentPanelRepository {
	return core.NewTranslationAssignmentPanelRepository(repo)
}

func NewTranslationExchangeService(store TranslationExchangeStore) *TranslationExchangeService {
	return core.NewTranslationExchangeService(store)
}

func NewTranslationQueuePanel(repo Repository) *PanelBuilder {
	return core.NewTranslationQueuePanel(repo)
}

func NewUserManagementModule(opts ...UserManagementModuleOption) *UserManagementModule {
	return core.NewUserManagementModule(opts...)
}

func NewUserManagementService(users UserRepository, roles RoleRepository) *UserManagementService {
	return core.NewUserManagementService(users, roles)
}

func NewUserPanelRepository(service *UserManagementService) *UserPanelRepository {
	return core.NewUserPanelRepository(service)
}

func NewUserProfilesPanelRepository(users *UserManagementService, profiles ProfileStore, defaultLocale string) *UserProfilesPanelRepository {
	return core.NewUserProfilesPanelRepository(users, profiles, defaultLocale)
}

func NewWidgetDefinitionRepository(widgets CMSWidgetService) *WidgetDefinitionRepository {
	return core.NewWidgetDefinitionRepository(widgets)
}

func NewWidgetInstanceRepository(widgets CMSWidgetService) *WidgetInstanceRepository {
	return core.NewWidgetInstanceRepository(widgets)
}

func NewWorkflowRuntimeService(workflows WorkflowDefinitionRepository, bindings WorkflowBindingRepository) *WorkflowRuntimeService {
	return core.NewWorkflowRuntimeService(workflows, bindings)
}

func NormalizeBasePath(basePath string) string {
	return core.NormalizeBasePath(basePath)
}

func NormalizeFilterType(raw string) string {
	return core.NormalizeFilterType(raw)
}

func NormalizeListPredicates(opts ListOptions) []ListPredicate {
	return core.NormalizeListPredicates(opts)
}

func NormalizeMenuItemTranslationFields(item MenuItem) (string, string, string, string) {
	return core.NormalizeMenuItemTranslationFields(item)
}

func NormalizeMenuItemType(raw string) string {
	return core.NormalizeMenuItemType(raw)
}

func NormalizeMenuSlug(raw string) string {
	return core.NormalizeMenuSlug(raw)
}

func ParseIconReference(value string) IconReference {
	return core.ParseIconReference(value)
}

func ParseListPredicateKey(key string) (string, string) {
	return core.ParseListPredicateKey(key)
}

func PermissionMatrixDescriptor(basePath string) components.Descriptor {
	return core.PermissionMatrixDescriptor(basePath)
}

func PrefixBasePath(basePath string, routePath string) string {
	return core.PrefixBasePath(basePath, routePath)
}

func RateLimitError() error {
	return core.RateLimitError()
}

func RegisterBuiltinIconLibraries(svc *IconService) error {
	return core.RegisterBuiltinIconLibraries(svc)
}

func RegisterCommand[T any](bus *CommandBus, cmd command.Commander[T], runnerOpts ...runner.Option) (dispatcher.Subscription, error) {
	return core.RegisterCommand[T](bus, cmd, runnerOpts...)
}

func RegisterCoreCommandFactories(bus *CommandBus) error {
	return core.RegisterCoreCommandFactories(bus)
}

func RegisterDashboardProviderFactory(bus *CommandBus, commandName string, code string, defaultConfig map[string]any) error {
	return core.RegisterDashboardProviderFactory(bus, commandName, code, defaultConfig)
}

func RegisterDefaultCMSWorkflows(registrar WorkflowRegistrar) {
	core.RegisterDefaultCMSWorkflows(registrar)
}

func RegisterDeliveryGraphQLSchemas() {
	core.RegisterDeliveryGraphQLSchemas()
}

func RegisterDoctorDebugPanel(admin *Admin) {
	core.RegisterDoctorDebugPanel(admin)
}

func RegisterDomainErrorCodes(codes ...DomainErrorCode) {
	core.RegisterDomainErrorCodes(codes...)
}

func RegisterManagementGraphQLSchemas() {
	core.RegisterManagementGraphQLSchemas()
}

func RegisterMessageFactory[T any](bus *CommandBus, name string, build func(payload map[string]any, ids []string) (T, error)) error {
	return core.RegisterMessageFactory[T](bus, name, build)
}

func RegisterPermissionsDebugPanel(admin *Admin) {
	core.RegisterPermissionsDebugPanel(admin)
}

func RegisterQuery[T any, R any](bus *CommandBus, qry command.Querier[T, R], runnerOpts ...runner.Option) (dispatcher.Subscription, error) {
	return core.RegisterQuery[T, R](bus, qry, runnerOpts...)
}

func RegisterTranslationExchangeCommandFactories(bus *CommandBus) error {
	return core.RegisterTranslationExchangeCommandFactories(bus)
}

func RegisterTranslationProgressWidget(dash *Dashboard, stats TranslationQueueStatsService, urls urlkit.Resolver) {
	core.RegisterTranslationProgressWidget(dash, stats, urls)
}

func RegisterTranslationQueueCommandFactories(bus *CommandBus) error {
	return core.RegisterTranslationQueueCommandFactories(bus)
}

func RegisterTranslationQueueCommands(bus *CommandBus, service TranslationQueueService) error {
	return core.RegisterTranslationQueueCommands(bus, service)
}

func RegisterTranslationQueuePanel(admin *Admin, repo TranslationAssignmentRepository) (*Panel, error) {
	return core.RegisterTranslationQueuePanel(admin, repo)
}

func RegisterTranslationQueueTabs(admin *Admin) error {
	return core.RegisterTranslationQueueTabs(admin)
}

func RenderOptionsForAPI(trusted bool) IconRenderOptions {
	return core.RenderOptionsForAPI(trusted)
}

func RenderOptionsForModule() IconRenderOptions {
	return core.RenderOptionsForModule()
}

func RenderOptionsForTemplate() IconRenderOptions {
	return core.RenderOptionsForTemplate()
}

func ResolveTranslationExchangeLinkageKey(row TranslationExchangeRow) (TranslationExchangeLinkageKey, error) {
	return core.ResolveTranslationExchangeLinkageKey(row)
}

func SchemaEditorDescriptor(basePath string) components.Descriptor {
	return core.SchemaEditorDescriptor(basePath)
}

func SetDefaultErrorPresenter(presenter ErrorPresenter) {
	core.SetDefaultErrorPresenter(presenter)
}

func ThemeSelectorFromContext(ctx context.Context) ThemeSelector {
	return core.ThemeSelectorFromContext(ctx)
}

func TranslationCapabilities(adm *Admin) map[string]any {
	return core.TranslationCapabilities(adm)
}

func TranslationCapabilitiesForContext(adm *Admin, reqCtx context.Context) map[string]any {
	return core.TranslationCapabilitiesForContext(adm, reqCtx)
}

func TranslationSharedContractsPayload() map[string]any {
	return core.TranslationSharedContractsPayload()
}

func TranslationSourceTargetDriftContract() map[string]any {
	return core.TranslationSourceTargetDriftContract()
}

func TranslationStatusEnumContract() map[string]any {
	return core.TranslationStatusEnumContract()
}

func ValidateJSONPointerFormat(pointer string) bool {
	return core.ValidateJSONPointerFormat(pointer)
}

func WithActivityRetention(limit int) func(*ActivityFeed) {
	return core.WithActivityRetention(limit)
}

func WithAuthErrorHandler(handler func(router.Context, error) error) GoAuthAuthenticatorOption {
	return core.WithAuthErrorHandler(handler)
}

func WithBunBaseCriteria[T any](criteria ...repository.SelectCriteria) BunRepositoryOption[T] {
	return core.WithBunBaseCriteria[T](criteria...)
}

func WithBunDeleteCriteria[T any](criteria ...repository.DeleteCriteria) BunRepositoryOption[T] {
	return core.WithBunDeleteCriteria[T](criteria...)
}

func WithBunFilterMapping[T any](builders map[string]func(any) repository.SelectCriteria) BunRepositoryOption[T] {
	return core.WithBunFilterMapping[T](builders)
}

func WithBunPatchAllowedFields[T any](fields ...string) BunRepositoryOption[T] {
	return core.WithBunPatchAllowedFields[T](fields...)
}

func WithBunRecordMapper[T any](mapper BunRecordMapper[T]) BunRepositoryOption[T] {
	return core.WithBunRecordMapper[T](mapper)
}

func WithBunSearchColumns[T any](columns ...string) BunRepositoryOption[T] {
	return core.WithBunSearchColumns[T](columns...)
}

func WithBunUpdateCriteria[T any](criteria ...repository.UpdateCriteria) BunRepositoryOption[T] {
	return core.WithBunUpdateCriteria[T](criteria...)
}

func WithContentTypeBuilderBasePath(path string) ContentTypeBuilderOption {
	return core.WithContentTypeBuilderBasePath(path)
}

func WithContentTypeBuilderEntryMenuParent(menuParent string) ContentTypeBuilderOption {
	return core.WithContentTypeBuilderEntryMenuParent(menuParent)
}

func WithContentTypeBuilderGuardrails(guardrails *SchemaGuardrails) ContentTypeBuilderOption {
	return core.WithContentTypeBuilderGuardrails(guardrails)
}

func WithContentTypeBuilderMenu(menuCode string, menuParent string) ContentTypeBuilderOption {
	return core.WithContentTypeBuilderMenu(menuCode, menuParent)
}

func WithContentTypeBuilderPanelFactory(factory *DynamicPanelFactory) ContentTypeBuilderOption {
	return core.WithContentTypeBuilderPanelFactory(factory)
}

func WithContentTypeBuilderPermission(permission string) ContentTypeBuilderOption {
	return core.WithContentTypeBuilderPermission(permission)
}

func WithContentTypeBuilderPreviewFallback(fallback SchemaPreviewFallback) ContentTypeBuilderOption {
	return core.WithContentTypeBuilderPreviewFallback(fallback)
}

func WithContentTypeBuilderRateLimiter(limiter *RateLimiter) ContentTypeBuilderOption {
	return core.WithContentTypeBuilderRateLimiter(limiter)
}

func WithContentTypeBuilderSchemaValidator(validator SchemaValidator) ContentTypeBuilderOption {
	return core.WithContentTypeBuilderSchemaValidator(validator)
}

func WithContentTypeBuilderWorkflow(workflow WorkflowEngine) ContentTypeBuilderOption {
	return core.WithContentTypeBuilderWorkflow(workflow)
}

func WithContentTypeBuilderWorkflowAuthorizer(authorizer WorkflowAuthorizer) ContentTypeBuilderOption {
	return core.WithContentTypeBuilderWorkflowAuthorizer(authorizer)
}

func WithDefaultLibrary(library string) IconServiceOption {
	return core.WithDefaultLibrary(library)
}

func WithDefaultVariant(variant string) IconServiceOption {
	return core.WithDefaultVariant(variant)
}

func WithDeleteMissing(enabled bool) PreferencesOption {
	return core.WithDeleteMissing(enabled)
}

func WithDerivedFields() CMSContentListOption {
	return core.WithDerivedFields()
}

func WithDynamicPanelHooks(hooks DynamicPanelHooks) DynamicPanelFactoryOption {
	return core.WithDynamicPanelHooks(hooks)
}

func WithDynamicPanelMenu(basePath string, menuCode string, menuParent string, locale string) DynamicPanelFactoryOption {
	return core.WithDynamicPanelMenu(basePath, menuCode, menuParent, locale)
}

func WithDynamicPanelSchemaConverter(converter *SchemaToFieldsConverter) DynamicPanelFactoryOption {
	return core.WithDynamicPanelSchemaConverter(converter)
}

func WithDynamicPanelSchemaValidator(validator SchemaValidator) DynamicPanelFactoryOption {
	return core.WithDynamicPanelSchemaValidator(validator)
}

func WithEnvironment(ctx context.Context, environment string) context.Context {
	return core.WithEnvironment(ctx, environment)
}

func WithFallbackIcon(icon string) IconServiceOption {
	return core.WithFallbackIcon(icon)
}

func WithIconSecurityPolicy(policy IconSecurityPolicy) IconServiceOption {
	return core.WithIconSecurityPolicy(policy)
}

func WithIconServiceLogger(logger Logger) IconServiceOption {
	return core.WithIconServiceLogger(logger)
}

func WithKeyPrefix(prefix string) PreferencesOption {
	return core.WithKeyPrefix(prefix)
}

func WithKeys(keys ...string) PreferencesOption {
	return core.WithKeys(keys...)
}

func WithLocale(ctx context.Context, locale string) context.Context {
	return core.WithLocale(ctx, locale)
}

func WithMenuPositions(usersPos *int, rolesPos *int) UserManagementModuleOption {
	return core.WithMenuPositions(usersPos, rolesPos)
}

func WithOptionalAuth(optional bool) GoAuthAuthenticatorOption {
	return core.WithOptionalAuth(optional)
}

func WithRolesPanelConfigurer(fn func(*PanelBuilder) *PanelBuilder) UserManagementModuleOption {
	return core.WithRolesPanelConfigurer(fn)
}

func WithSchemaMaxDepth(depth int) SchemaGuardrailsOption {
	return core.WithSchemaMaxDepth(depth)
}

func WithSchemaMaxFields(count int) SchemaGuardrailsOption {
	return core.WithSchemaMaxFields(count)
}

func WithSchemaMaxSize(bytes int) SchemaGuardrailsOption {
	return core.WithSchemaMaxSize(bytes)
}

func WithStack(err error) error {
	return core.WithStack(err)
}

func WithThemeSelection(ctx context.Context, selector ThemeSelector) context.Context {
	return core.WithThemeSelection(ctx, selector)
}

func WithTranslations() CMSContentListOption {
	return core.WithTranslations()
}

func WithUserMenuParent(parent string) UserManagementModuleOption {
	return core.WithUserMenuParent(parent)
}

func WithUserPanelTabs(tabs ...PanelTab) UserManagementModuleOption {
	return core.WithUserPanelTabs(tabs...)
}

func WithUserProfilesPanel() UserManagementModuleOption {
	return core.WithUserProfilesPanel()
}

func WithUserProfilesPanelConfigurer(fn func(*PanelBuilder) *PanelBuilder) UserManagementModuleOption {
	return core.WithUserProfilesPanelConfigurer(fn)
}

func WithUsersPanelConfigurer(fn func(*PanelBuilder) *PanelBuilder) UserManagementModuleOption {
	return core.WithUsersPanelConfigurer(fn)
}

func WithWorkflowExtraCheck(fn func(context.Context, TransitionInput) bool) RoleWorkflowAuthorizerOption {
	return core.WithWorkflowExtraCheck(fn)
}

func WithWorkflowPermission(resource string, permission string) RoleWorkflowAuthorizerOption {
	return core.WithWorkflowPermission(resource, permission)
}

// ---- MANUAL COMPATIBILITY SECTION (MINIMAL) ----
// IntPtr is retained for backward compatibility with existing pkg/admin consumers.
func IntPtr(v int) *int {
	return &v
}

// ---- END MANUAL COMPATIBILITY SECTION ----
